<a href="https://colab.research.google.com/github/Jatingpt/Only-for-practicing/blob/main/Only_Practice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#If else statement
marks = 89
if marks>85:
  print("You will go for a trip")
elif marks>75 and marks<85:
  print("You are a good student")
else:
  print("Needs improvement")

You will go for a trip


In [ ]:
def marks(num):
  if num>80:
    print("You will get a mobile")
  else:
    print("You really need an improvement.")

marks(89)


You will get a mobile


In [ ]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(1,11):
  if i == 5:
    print("You are dismissed")
  else:
    print(i)

1
2
3
4
You are dismissed
6
7
8
9
10


In [ ]:
def add(x,y):
  print(x+y)

add(3,4)

7


In [ ]:
a = ["Rohit", "Sohan", "Mohan", "Priya", "Greena"]
print(a)

['Rohit', 'Sohan', 'Mohan', 'Priya', 'Greena']


In [ ]:
print(a[1])

Sohan


In [ ]:
print(a[::-1])
print()
print(a[:2])
print(a[-3:-1])

['Greena', 'Priya', 'Mohan', 'Sohan', 'Rohit']

['Rohit', 'Sohan']
['Mohan', 'Priya']


In [ ]:
print(a[1:3])

['Sohan', 'Mohan']


In [ ]:
for i in range(1,101):
  if i%8==0 and i%12==0:
    print(i)

24
48
72
96


In [ ]:
#2*3.14*r
def area(r):
  print(2*3.14*r)

area(7)


43.96


In [ ]:
def rect_area(length,breath):
  print(length*breath)

rect_area(4,3)

12


In [ ]:
a = 1,2,3
b = "1,2,3"
a is b

False

In [ ]:
def mul(n):
  print(7*n)

mul(7)

49


In [ ]:
n = 7
for i in range(1,11):
  print(7*i)

7
14
21
28
35
42
49
56
63
70


In [ ]:
marks = 98
print("You are a good student") if marks>90 else print("You are an average student")

You are a good student


In [ ]:
a = 7
b = 1
while b<=10:
  print(a*b)
  b+=1

7
14
21
28
35
42
49
56
63
70


In [ ]:
#Numpy stands for numeric python.
#deals with array.
#a library of python.
#numpy stores less memory.
#directly apply the math functions.
#performing faster.

import numpy as np

a = np.array([1,2,3,4])
print(a)

print(type(a))

print()

#Math operation in list
a = [1,2,3,4,5]
b = [1,2,3,4,5]
print(a+b)

print()


a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

print(a+b)

[1 2 3 4]
<class 'numpy.ndarray'>

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

[ 2  4  6  8 10]


In [ ]:
arr = np.array([10, 23, 24, 25, 53, 53, 53])
print(arr)


print(arr[1])

[10 23 24 25 53 53 53]
23


In [ ]:
#One-Dimensional Array.

a = np.array([3,4,5,2,3,6])
print(a)


#Slicing in one dimensional array.
a = np.array([3,4,5,2,3,6])
a[::-1]

[3 4 5 2 3 6]


array([6, 3, 2, 5, 4, 3])

In [ ]:
#2-dimensional array.

a = np.array([[1,2],
             [3,4]])
print(a)

#slicing in 2-dimensional array.
a = np.array([[1,2],
             [3,4]])

print(a[1])

print()

print(a[0])

print()

print(a[0:1])

print()

print(a[0:2])

print()

print(a[1][1])

[[1 2]
 [3 4]]
[3 4]

[1 2]

[[1 2]]

[[1 2]
 [3 4]]

4


In [ ]:
#3-dimensional array.

a = np.array([[[12,13,14],
               [12,13,14],
               [12,13,14]]])
print(a)

[[[12 13 14]
  [12 13 14]
  [12 13 14]]]


In [ ]:
#Slicing in the 3-dimensional numpy array.
import numpy as np
a = np.array([[[12,13,14],
               [12,13,14],
               [12,13,14]]])
print(np.ndim(a))

3


In [ ]:
a = np.array([[1,2],
             [3,4]])
print(np.ndim(a))

2


In [ ]:
import numpy as np
a = np.array([[[12,3,4],
               [12,1,1],
               [12,3,1]]])

print(a[0][1])
print()
print(a[0][2])
print()
print(a[0][1])
print()
print(a[0][1][1])
print()
print(a[0][2][1])

[12  1  1]

[12  3  1]

[12  1  1]

1

3


In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

print(type(a))
print()
print(a.astype(int))
print()
print(len(a))
print()
print(a.shape)
print()
print(a.size)
print()
print(a.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>

[1 2 3 4 5]

5

(5,)

5

1


In [ ]:
a = np.array([[1,2],[3,4]])
print(type(a))
print(a.ndim)
print(a.size)
print(a.dtype)
print(len(a))

<class 'numpy.ndarray'>
2
4
int64
2


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(arr1+arr2)

[[ 6  8]
 [10 12]]


In [ ]:
b = np.concatenate([arr1,arr2])
print(len(b))
print(b)


4
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(b[3][1])

8


In [ ]:
#spliting in array
arry = np.array([1,2,3,4,5,6])
print(np.array_split(arry,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
c = np.array([1,2,3,4,5,6,7,8,9])
d = np.array_split(c,5)

In [ ]:
print(d[1])

[3 4]


In [ ]:
a = np.array([1,2,3,4,5])
np.append(a,6)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.insert(a,1,8)

array([1, 8, 2, 3, 4, 5])

In [ ]:
np.delete(a,[1])

array([1, 3, 4, 5])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.ndim

1

In [ ]:
len(arr)

8

In [ ]:
arr.size

8

In [ ]:
arr.shape

(8,)

In [ ]:
a = np.array([[1,2],[3,4]])
a.shape

(2, 2)

In [ ]:
arr = np.array([1,2,3,4,5,6])
np.append(arr,2)

array([1, 2, 3, 4, 5, 6, 2])

In [ ]:
np.insert(arr,1,9)

array([1, 9, 2, 3, 4, 5, 6])

In [ ]:
np.delete(arr,[1])

array([1, 3, 4, 5, 6])

In [ ]:
print(arr.size)
print(arr.dtype)
print(arr.ndim)
print(arr.astype(int))
print(len(arr))

6
int64
1
[1 2 3 4 5 6]
6


In [ ]:
hel = np.array([23,4,53,2,5,3,6,72])
print(np.sort(hel))

[ 2  3  4  5  6 23 53 72]


In [ ]:
a = np.array([1,2,3,4])
np.where(a==2)

(array([1]),)

In [ ]:
np.where(arr==4)

(array([3]),)

In [ ]:
#filtering the array manually
arry = np.array([1,2,3,4])
fa = [True,False,True,False]
new = arry[fa]
print(new)

[1 3]


In [ ]:
elem = np.array([1,2,3,4,5,6])
s = np.where(elem%2==0)
print(s)

(array([1, 3, 5]),)


In [ ]:
#Creating a dictionary.
#Dictionary allows the user to write the data in the form of key and its values.
#The keys and values are separated by semicolon.
#We are using a curly brackets to create a dictionary.

employee = {"Name": "John", "Age": 34, "Gender": "Male"}
print(employee)

{'Name': 'John', 'Age': 34, 'Gender': 'Male'}


In [ ]:
print(employee["Name"])
print(employee["Age"])
print(employee["Gender"])

John
34
Male


In [ ]:
import pandas as pd

In [ ]:
employee = {"Name": ["John"], "Age": [34], "Gender": ["Male"]}
df = pd.DataFrame(employee)
df

Name  Age Gender
0  John   34   Male

In [ ]:
employee = {"name": ["john", "robin", "kailash"],
            "age": [23, 45, 56],
            "Gender": ["Male", "Male", "Male"]}
df = pd.DataFrame(employee)
df

name  age Gender
0     john   23   Male
1    robin   45   Male
2  kailash   56   Male

In [ ]:
for i in employee:
  print(i)

name
age
Gender


In [ ]:
for i in employee:
  print(employee[i])

['john', 'robin', 'kailash']
[23, 45, 56]
['Male', 'Male', 'Male']


In [ ]:
print(employee.items())

dict_items([('name', ['john', 'robin', 'kailash']), ('age', [23, 45, 56]), ('Gender', ['Male', 'Male', 'Male'])])


In [ ]:
print(employee["name"])

['john', 'robin', 'kailash']


In [ ]:
for x,y in employee.items():
  print(x,y)

name ['john', 'robin', 'kailash']
age [23, 45, 56]
Gender ['Male', 'Male', 'Male']


In [ ]:
for x in employee.values():
  print(x)

['john', 'robin', 'kailash']
[23, 45, 56]
['Male', 'Male', 'Male']


In [ ]:
for x in employee.keys():
  print(x)

name
age
Gender


In [ ]:
for i in range(1,202):
  if i%8==0 and i%12==0:
    print(i)

24
48
72
96
120
144
168
192


In [ ]:
def add(x,y):
  print(x+y)

add(2,3)

5


In [ ]:
def area_square(side):
  print(side*side)

area_square(4)

16


In [ ]:
for i in range(1,3):
  for j in range(1,5):
    print(j)

1
2
3
4
1
2
3
4


In [ ]:
#Sets = sets are the collections of unique datas.


In [ ]:
num1 = int(input("Enter a number here: "))
num2 = int(input("Enter another number here: "))
print(num1+num2)

Enter a number here: 8
Enter another number here: 8
16


In [ ]:
def add():
  num1 = int(input('Enter a number here: '))
  num2 = int(input('Enter another number here: '))
  print(num1+num2)

add()

Enter a number here: 7
Enter another number here: 7
14


In [ ]:
a = 1.23
b = int(a)
b

1

In [ ]:
type(b)

int

In [ ]:
name = input("Enter your name here: ")
age = int(input("Enter your age here: "))
roll_no = int(input("Enter your roll number here: "))
gender = input("Enter your gender here: ")

Enter your name here: Jasleen
Enter your age here: 23
Enter your roll number here: 21
Enter your gender here: Male


In [ ]:
#creating a nested dictionary.
dict = {1: {"Name": "John", "Age": 23, "Gender": "Male"},
        2: {"Name": "Preeti", "Age": 32, "Gender": "Female"}}
print(dict)

{1: {'Name': 'John', 'Age': 23, 'Gender': 'Male'}, 2: {'Name': 'Preeti', 'Age': 32, 'Gender': 'Female'}}


In [ ]:
print(dict[1])

{'Name': 'John', 'Age': 23, 'Gender': 'Male'}


In [ ]:
print(dict[1]["Name"])

John


In [ ]:
dict = {"Name": "John", "Age": 23, "Gender": "Male"}
print(dict)

{'Name': 'John', 'Age': 23, 'Gender': 'Male'}


In [ ]:
dict.keys()

dict_keys(['Name', 'Age', 'Gender'])

In [ ]:
dict.values()

dict_values(['John', 23, 'Male'])

In [ ]:
dict.get("Name")

'John'

In [ ]:
dict.items()

dict_items([('Name', 'John'), ('Age', 23), ('Gender', 'Male')])

In [ ]:
dict.setdefault("Age",24)

23

In [ ]:
print(dict["Age"])

23


In [ ]:
#Iteration in dictionary.
a = {1,2,3,4,5}
for i in a:
  print(i, end = " ")

1 2 3 4 5 

In [ ]:
dict = {"Name": "John", "Age": 23, "Gender": "Male"}

for x in dict.values():
  print(x)

John
23
Male


In [ ]:
for x in dict.keys():
  print(x)

Name
Age
Gender


In [ ]:
for x,y in dict.items():
  print(x,y)

Name John
Age 23
Gender Male


In [ ]:
#Sets
a = {"Ironman", "Thor", "Bahubali", "Superman"}


In [ ]:
a.pop()
print(a)

{'Bahubali', 'Superman', 'Thor'}


In [ ]:
a

{'Bahubali', 'Superman', 'Thor'}

In [ ]:
a.add("Batman")

In [ ]:
a

{'Bahubali', 'Batman', 'Superman', 'Thor'}

In [ ]:
a.remove("Superman")
print(a)

{'Bahubali', 'Thor', 'Batman'}


In [ ]:
a.discard("Thor")
a

{'Bahubali', 'Batman'}

In [ ]:
b = a.copy()
print(b)

{'Bahubali', 'Batman'}


In [ ]:
list1 = [1,2,3,4,5]
list1.append(6)
print(list1)

[1, 2, 3, 4, 5, 6]


In [ ]:
list1.remove(6)
print(list1)

[1, 2, 3, 4, 5]


In [ ]:
list1.pop()

5

In [ ]:
list1

[1, 2, 3, 4]

In [ ]:
list1.append(5)
print(list1)

[1, 2, 3, 4, 5, 5]


In [ ]:
list1.count(2)  #to count the occurence of the element in the list.

1

In [ ]:
list1.insert(1,7)
print(list1)

[1, 7, 7, 7, 7, 2, 3, 4, 5, 5]


In [ ]:
list1.pop(2)

7

In [ ]:
avengers = ["Spiderman", "Batman", "Krish"]
avengers[0]

'Spiderman'

In [ ]:
avengers.append("Hulk")
print(avengers)

['Spiderman', 'Batman', 'Krish', 'Hulk', 'Hulk']


In [ ]:
avengers.remove("Hulk")

In [ ]:
print(avengers)

['Spiderman', 'Batman', 'Krish', 'Hulk']


In [ ]:
#write a program to find a sum of all even numbers upto 50.
sum = 0
for i in range(1,51):
  if num % 2== 0:
    sum+=i
print("The sum of the even numbers upto 50 is ", sum)

The sum of the even numbers upto 50 is  1275


In [ ]:
a = ["Jammu", "New Delhi", "Mumbai"]
b = ["Madhya Pradesh", "Shimla"]
print(a+b)

['Jammu', 'New Delhi', 'Mumbai', 'Madhya Pradesh', 'Shimla']


In [ ]:
a = ["Jammu", "New Delhi", "Mumbai"]
b = ["Madhya Pradesh", "Shimla"]
print(a[1])
print()
print(a.index("Jammu"))

New Delhi

0
None


In [ ]:
a = ["Jammu", "New Delhi", "Mumbai"]
b = ["Madhya Pradesh", "Shimla"]
a.extend(b)
print(a)

['Jammu', 'New Delhi', 'Mumbai', 'Madhya Pradesh', 'Shimla']


In [ ]:
a.index("New Delhi")

1

In [ ]:
num = []
for num in range(1,51):
  if i%2==0:
    num=i
print(num)

100


In [ ]:
sum = 0
for i in range(1,51):
  if num % 2== 0:
    sum+=i
print(sum)

1275


In [ ]:
name = "Jasmine"
age = 23
address = "L-83 Border Street New Delhi-110033"
print(name)
print(age)
print(address)

Jasmine
23
L-83 Border Street New Delhi-110033


In [ ]:
a = "Rohit, Raj"
b = "Rani, Shalini"
a,b = b,a

In [ ]:
print(a)

Rani, Shalini


In [ ]:
a = 1.23
b = int(a)
print(b)

1


In [ ]:
name = input("Enter a name here: ")
age = int(input("Enter your age here: "))
gender = input("Enter your gender here: ")

Enter a name here: Hira Lal
Enter your age here: 43
Enter your gender here: Male


In [ ]:
user_input = int(input("Enter number here: "))
user_input = float(user_input)
print(user_input)

Enter number here: 3
3.0


In [ ]:
#Logical operators- AND, OR, NOT
3>2 and 2<4

True

In [ ]:
3>1 or 3<4

True

In [ ]:
not(3>1 or 3<1)

False

In [ ]:
not(1>2 and 0>1)

True

In [ ]:
a = 123
b = "123"
print(a is b)
print(a is not b)

False
True


In [ ]:
a = "aeiou"
"i" in a
"ei" in a

True

In [ ]:
amount = 45
if amount >50:
  print("He is a rich person")
elif amount > 40:
  print("He is going to be rice")
else:
  print("He is a happy person.")

He is going to be rice


In [ ]:
for i in range(1,5):
  if i == 2:
    continue
  else:
    print(i)

1
3
4


In [ ]:
for i in range(1,11):
  if i == 5:
    break
  else:
    print(i)

1
2
3
4


In [ ]:
x = lambda a,b,c: (a+b)*c
x(1,2,3)

9

In [ ]:
[i for i in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
count = 1
while count<=5:
  print(count)
  count+=1

1
2
3
4
5


In [ ]:

student = {"name": "Rashi", "age": 34, "roll no": 23, "gender": "female"}
for x in student:
  print(x)

name
age
roll no
gender


In [ ]:
student = {"name": "Rashi", "age": 34, "roll no": 23, "gender": "female"}
for x in student.items():
  print(x)

('name', 'Rashi')
('age', 34)
('roll no', 23)
('gender', 'female')


In [ ]:
student = {"name": "Rashi", "age": 34, "roll no": 23, "gender": "female"}
for x in student.values():
  print(x)


Rashi
34
23
female


In [ ]:
student = {"name": "Rashi", "age": 34, "roll no": 23, "gender": "female"}
for i in student.keys():
  print(i)

name
age
roll no
gender


In [ ]:
                                    ##Python from the start.
print("hello world")

hello world


In [ ]:
#data types in python- Text datatypes, integer dtypes, sequence dtypes, map dtypes,
#String, int, float, boolean, list, tuple, dictionary.

In [ ]:
#Taking the inputs from the user.
name = input("Enter a name here: ")
age = int(input("Enter the age here: "))
gender = input("Enter the gender here: ")

Enter a name here: Lara
Enter the age here: 23
Enter the gender here: Female


In [ ]:
#String- Whatever is comes under the inverted comma called string. It can be anything like int, float, boolean, text anything.

In [ ]:
#Typecasting- 2 Types of typecasting occurs
#1. Implicit- During the time of conversion or while performing the task python can change the dtypes by itself.
#2. Explicit- User has to change the dtypes from one type to another.

#Implicit
a = 123
b = 1.23
print(a+b)


#Explicit
a = 1.23
b = "123"
b = float(b)
print(a+b)

124.23
124.23


In [ ]:
                                                    #QUESTIONS
#Write a program to swap two variable.
a = "1,2,3"
b = "3,4,5"
a,b = b,a
print(a)
print(b)

#converting float into integer.
a = 1.23
b = int(a)
print(b)

3,4,5
1,2,3
1


In [ ]:
#Write the program to fill the id card for a student.
def student_details():
  input("Enter the name of the person: ")
  input("Enter the age of the person: ")
  input("Enter the roll number of the person: ")

student_details()

Enter the name of the person: Alisha
Enter the age of the person: 23
Enter the roll number of the person: 21


In [ ]:
#Take the user input as an integer and convert it into float.
                                          #Check because this function is running but not correctly
def convert():
  user_input = int(input("Enter the float number here: "))
  user_input = float(user_input)

convert()

Enter the float number here: 9


In [ ]:
#Here we have total 6 types of operators-
#Arithmatic Operator - addition(+), substraction(-) etc
#Comparision Operator - "==", "<=" ">=" etc
#Identity Operator - "is" or "is not"
#Membership Operator- "in" or "not in"
#Logical Operator- AND, OR, NOT
#Assignment Operator-

In [21]:
sugar = 350
if sugar>400:
  print("You will be in danger soon.")
elif sugar> 300 and sugar<=400:
  print("You should immidiatly take the prevention")
else:
  print("Do excercise daily.")

You should immidiatly take the prevention


In [22]:
marks = 68
print("You will go for picnic") if marks>70 else print("Go and read again then come for exams")

Go and read again then come for exams


In [23]:
x = lambda a,b,c: (a+b)*c
x(3,3,5)

30