<a href="https://colab.research.google.com/github/Jatingpt/Only-for-practicing/blob/main/Only_Practice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#If else statement
marks = 89
if marks>85:
  print("You will go for a trip")
elif marks>75 and marks<85:
  print("You are a good student")
else:
  print("Needs improvement")

You will go for a trip


In [ ]:
def marks(num):
  if num>80:
    print("You will get a mobile")
  else:
    print("You really need an improvement.")

marks(89)


You will get a mobile


In [ ]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(1,11):
  if i == 5:
    print("You are dismissed")
  else:
    print(i)

1
2
3
4
You are dismissed
6
7
8
9
10


In [ ]:
def add(x,y):
  print(x+y)

add(3,4)

7


In [ ]:
a = ["Rohit", "Sohan", "Mohan", "Priya", "Greena"]
print(a)

['Rohit', 'Sohan', 'Mohan', 'Priya', 'Greena']


In [ ]:
print(a[1])

Sohan


In [ ]:
print(a[::-1])
print()
print(a[:2])
print(a[-3:-1])

['Greena', 'Priya', 'Mohan', 'Sohan', 'Rohit']

['Rohit', 'Sohan']
['Mohan', 'Priya']


In [ ]:
print(a[1:3])

['Sohan', 'Mohan']


In [ ]:
for i in range(1,101):
  if i%8==0 and i%12==0:
    print(i)

24
48
72
96


In [ ]:
#2*3.14*r
def area(r):
  print(2*3.14*r)

area(7)


43.96


In [ ]:
def rect_area(length,breath):
  print(length*breath)

rect_area(4,3)

12


In [ ]:
a = 1,2,3
b = "1,2,3"
a is b

False

In [ ]:
def mul(n):
  print(7*n)

mul(7)

49


In [ ]:
n = 7
for i in range(1,11):
  print(7*i)

7
14
21
28
35
42
49
56
63
70


In [ ]:
marks = 98
print("You are a good student") if marks>90 else print("You are an average student")

You are a good student


In [ ]:
a = 7
b = 1
while b<=10:
  print(a*b)
  b+=1

7
14
21
28
35
42
49
56
63
70


In [ ]:
#Numpy stands for numeric python.
#deals with array.
#a library of python.
#numpy stores less memory.
#directly apply the math functions.
#performing faster.

import numpy as np

a = np.array([1,2,3,4])
print(a)

print(type(a))

print()

#Math operation in list
a = [1,2,3,4,5]
b = [1,2,3,4,5]
print(a+b)

print()


a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

print(a+b)

[1 2 3 4]
<class 'numpy.ndarray'>

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

[ 2  4  6  8 10]


In [ ]:
arr = np.array([10, 23, 24, 25, 53, 53, 53])
print(arr)


print(arr[1])

[10 23 24 25 53 53 53]
23


In [ ]:
#One-Dimensional Array.

a = np.array([3,4,5,2,3,6])
print(a)


#Slicing in one dimensional array.
a = np.array([3,4,5,2,3,6])
a[::-1]

[3 4 5 2 3 6]


array([6, 3, 2, 5, 4, 3])

In [ ]:
#2-dimensional array.

a = np.array([[1,2],
             [3,4]])
print(a)

#slicing in 2-dimensional array.
a = np.array([[1,2],
             [3,4]])

print(a[1])

print()

print(a[0])

print()

print(a[0:1])

print()

print(a[0:2])

print()

print(a[1][1])

[[1 2]
 [3 4]]
[3 4]

[1 2]

[[1 2]]

[[1 2]
 [3 4]]

4


In [ ]:
#3-dimensional array.

a = np.array([[[12,13,14],
               [12,13,14],
               [12,13,14]]])
print(a)

[[[12 13 14]
  [12 13 14]
  [12 13 14]]]


In [ ]:
#Slicing in the 3-dimensional numpy array.
import numpy as np
a = np.array([[[12,13,14],
               [12,13,14],
               [12,13,14]]])
print(np.ndim(a))

3


In [ ]:
a = np.array([[1,2],
             [3,4]])
print(np.ndim(a))

2


In [ ]:
import numpy as np
a = np.array([[[12,3,4],
               [12,1,1],
               [12,3,1]]])

print(a[0][1])
print()
print(a[0][2])
print()
print(a[0][1])
print()
print(a[0][1][1])
print()
print(a[0][2][1])

[12  1  1]

[12  3  1]

[12  1  1]

1

3


In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

print(type(a))
print()
print(a.astype(int))
print()
print(len(a))
print()
print(a.shape)
print()
print(a.size)
print()
print(a.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>

[1 2 3 4 5]

5

(5,)

5

1


In [ ]:
a = np.array([[1,2],[3,4]])
print(type(a))
print(a.ndim)
print(a.size)
print(a.dtype)
print(len(a))

<class 'numpy.ndarray'>
2
4
int64
2


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(arr1+arr2)

[[ 6  8]
 [10 12]]


In [ ]:
b = np.concatenate([arr1,arr2])
print(len(b))
print(b)


4
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(b[3][1])

8


In [ ]:
#spliting in array
arry = np.array([1,2,3,4,5,6])
print(np.array_split(arry,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
c = np.array([1,2,3,4,5,6,7,8,9])
d = np.array_split(c,5)

In [ ]:
print(d[1])

[3 4]


In [ ]:
a = np.array([1,2,3,4,5])
np.append(a,6)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.insert(a,1,8)

array([1, 8, 2, 3, 4, 5])

In [ ]:
np.delete(a,[1])

array([1, 3, 4, 5])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.ndim

1

In [ ]:
len(arr)

8

In [ ]:
arr.size

8

In [ ]:
arr.shape

(8,)

In [ ]:
a = np.array([[1,2],[3,4]])
a.shape

(2, 2)

In [ ]:
arr = np.array([1,2,3,4,5,6])
np.append(arr,2)

array([1, 2, 3, 4, 5, 6, 2])

In [ ]:
np.insert(arr,1,9)

array([1, 9, 2, 3, 4, 5, 6])

In [ ]:
np.delete(arr,[1])

array([1, 3, 4, 5, 6])

In [ ]:
print(arr.size)
print(arr.dtype)
print(arr.ndim)
print(arr.astype(int))
print(len(arr))

6
int64
1
[1 2 3 4 5 6]
6


In [ ]:
hel = np.array([23,4,53,2,5,3,6,72])
print(np.sort(hel))

[ 2  3  4  5  6 23 53 72]


In [ ]:
a = np.array([1,2,3,4])
np.where(a==2)

(array([1]),)

In [ ]:
np.where(arr==4)

(array([3]),)

In [ ]:
#filtering the array manually
arry = np.array([1,2,3,4])
fa = [True,False,True,False]
new = arry[fa]
print(new)

[1 3]


In [ ]:
elem = np.array([1,2,3,4,5,6])
s = np.where(elem%2==0)
print(s)

(array([1, 3, 5]),)


In [ ]:
#Creating a dictionary.
#Dictionary allows the user to write the data in the form of key and its values.
#The keys and values are separated by semicolon.
#We are using a curly brackets to create a dictionary.

employee = {"Name": "John", "Age": 34, "Gender": "Male"}
print(employee)

{'Name': 'John', 'Age': 34, 'Gender': 'Male'}


In [ ]:
print(employee["Name"])
print(employee["Age"])
print(employee["Gender"])

John
34
Male


In [ ]:
import pandas as pd

In [ ]:
employee = {"Name": ["John"], "Age": [34], "Gender": ["Male"]}
df = pd.DataFrame(employee)
df

Name  Age Gender
0  John   34   Male

In [ ]:
employee = {"name": ["john", "robin", "kailash"],
            "age": [23, 45, 56],
            "Gender": ["Male", "Male", "Male"]}
df = pd.DataFrame(employee)
df

name  age Gender
0     john   23   Male
1    robin   45   Male
2  kailash   56   Male

In [ ]:
for i in employee:
  print(i)

name
age
Gender


In [ ]:
for i in employee:
  print(employee[i])

['john', 'robin', 'kailash']
[23, 45, 56]
['Male', 'Male', 'Male']


In [ ]:
print(employee.items())

dict_items([('name', ['john', 'robin', 'kailash']), ('age', [23, 45, 56]), ('Gender', ['Male', 'Male', 'Male'])])


In [ ]:
print(employee["name"])

['john', 'robin', 'kailash']


In [ ]:
for x,y in employee.items():
  print(x,y)

name ['john', 'robin', 'kailash']
age [23, 45, 56]
Gender ['Male', 'Male', 'Male']


In [ ]:
for x in employee.values():
  print(x)

['john', 'robin', 'kailash']
[23, 45, 56]
['Male', 'Male', 'Male']


In [ ]:
for x in employee.keys():
  print(x)

name
age
Gender


In [ ]:
for i in range(1,202):
  if i%8==0 and i%12==0:
    print(i)

24
48
72
96
120
144
168
192


In [ ]:
def add(x,y):
  print(x+y)

add(2,3)

5


In [ ]:
def area_square(side):
  print(side*side)

area_square(4)

16


In [ ]:
for i in range(1,3):
  for j in range(1,5):
    print(j)

1
2
3
4
1
2
3
4


In [ ]:
#Sets = sets are the collections of unique datas.


In [ ]:
num1 = int(input("Enter a number here: "))
num2 = int(input("Enter another number here: "))
print(num1+num2)

Enter a number here: 8
Enter another number here: 8
16


In [ ]:
def add():
  num1 = int(input('Enter a number here: '))
  num2 = int(input('Enter another number here: '))
  print(num1+num2)

add()

Enter a number here: 7
Enter another number here: 7
14


In [ ]:
a = 1.23
b = int(a)
b

1

In [ ]:
type(b)

int

In [ ]:
name = input("Enter your name here: ")
age = int(input("Enter your age here: "))
roll_no = int(input("Enter your roll number here: "))
gender = input("Enter your gender here: ")

Enter your name here: Jasleen
Enter your age here: 23
Enter your roll number here: 21
Enter your gender here: Male


In [3]:
#creating a nested dictionary.
dict = {1: {"Name": "John", "Age": 23, "Gender": "Male"},
        2: {"Name": "Preeti", "Age": 32, "Gender": "Female"}}
print(dict)

{1: {'Name': 'John', 'Age': 23, 'Gender': 'Male'}, 2: {'Name': 'Preeti', 'Age': 32, 'Gender': 'Female'}}


In [4]:
print(dict[1])

{'Name': 'John', 'Age': 23, 'Gender': 'Male'}


In [6]:
print(dict[1]["Name"])

John


In [7]:
dict = {"Name": "John", "Age": 23, "Gender": "Male"}
print(dict)

{'Name': 'John', 'Age': 23, 'Gender': 'Male'}


In [8]:
dict.keys()

dict_keys(['Name', 'Age', 'Gender'])

In [9]:
dict.values()

dict_values(['John', 23, 'Male'])

In [10]:
dict.get("Name")

'John'

In [11]:
dict.items()

dict_items([('Name', 'John'), ('Age', 23), ('Gender', 'Male')])

In [13]:
dict.setdefault("Age",24)

23

In [14]:
print(dict["Age"])

23


In [16]:
#Iteration in dictionary.
a = {1,2,3,4,5}
for i in a:
  print(i, end = " ")

1 2 3 4 5 

In [20]:
dict = {"Name": "John", "Age": 23, "Gender": "Male"}

for x in dict.values():
  print(x)

John
23
Male


In [22]:
for x in dict.keys():
  print(x)

Name
Age
Gender


In [23]:
for x,y in dict.items():
  print(x,y)

Name John
Age 23
Gender Male
