<a href="https://colab.research.google.com/github/Jatingpt/Only-for-practicing/blob/main/Only_Practice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#If else statement
marks = 89
if marks>85:
  print("You will go for a trip")
elif marks>75 and marks<85:
  print("You are a good student")
else:
  print("Needs improvement")

You will go for a trip


In [ ]:
def marks(num):
  if num>80:
    print("You will get a mobile")
  else:
    print("You really need an improvement.")

marks(89)


You will get a mobile


In [ ]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(1,11):
  if i == 5:
    print("You are dismissed")
  else:
    print(i)

1
2
3
4
You are dismissed
6
7
8
9
10


In [ ]:
def add(x,y):
  print(x+y)

add(3,4)

7


In [ ]:
a = ["Rohit", "Sohan", "Mohan", "Priya", "Greena"]
print(a)

['Rohit', 'Sohan', 'Mohan', 'Priya', 'Greena']


In [ ]:
print(a[1])

Sohan


In [ ]:
print(a[::-1])
print()
print(a[:2])
print(a[-3:-1])

['Greena', 'Priya', 'Mohan', 'Sohan', 'Rohit']

['Rohit', 'Sohan']
['Mohan', 'Priya']


In [ ]:
print(a[1:3])

['Sohan', 'Mohan']


In [ ]:
for i in range(1,101):
  if i%8==0 and i%12==0:
    print(i)

24
48
72
96


In [ ]:
#2*3.14*r
def area(r):
  print(2*3.14*r)

area(7)


43.96


In [ ]:
def rect_area(length,breath):
  print(length*breath)

rect_area(4,3)

12


In [ ]:
a = 1,2,3
b = "1,2,3"
a is b

False

In [ ]:
def mul(n):
  print(7*n)

mul(7)

49


In [ ]:
n = 7
for i in range(1,11):
  print(7*i)

7
14
21
28
35
42
49
56
63
70


In [ ]:
marks = 98
print("You are a good student") if marks>90 else print("You are an average student")

You are a good student


In [ ]:
a = 7
b = 1
while b<=10:
  print(a*b)
  b+=1

7
14
21
28
35
42
49
56
63
70


In [ ]:
#Numpy stands for numeric python.
#deals with array.
#a library of python.
#numpy stores less memory.
#directly apply the math functions.
#performing faster.

import numpy as np

a = np.array([1,2,3,4])
print(a)

print(type(a))

print()

#Math operation in list
a = [1,2,3,4,5]
b = [1,2,3,4,5]
print(a+b)

print()


a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

print(a+b)

[1 2 3 4]
<class 'numpy.ndarray'>

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

[ 2  4  6  8 10]


In [ ]:
arr = np.array([10, 23, 24, 25, 53, 53, 53])
print(arr)


print(arr[1])

[10 23 24 25 53 53 53]
23


In [ ]:
#One-Dimensional Array.

a = np.array([3,4,5,2,3,6])
print(a)


#Slicing in one dimensional array.
a = np.array([3,4,5,2,3,6])
a[::-1]

[3 4 5 2 3 6]


array([6, 3, 2, 5, 4, 3])

In [ ]:
#2-dimensional array.

a = np.array([[1,2],
             [3,4]])
print(a)

#slicing in 2-dimensional array.
a = np.array([[1,2],
             [3,4]])

print(a[1])

print()

print(a[0])

print()

print(a[0:1])

print()

print(a[0:2])

print()

print(a[1][1])

[[1 2]
 [3 4]]
[3 4]

[1 2]

[[1 2]]

[[1 2]
 [3 4]]

4


In [ ]:
#3-dimensional array.

a = np.array([[[12,13,14],
               [12,13,14],
               [12,13,14]]])
print(a)

[[[12 13 14]
  [12 13 14]
  [12 13 14]]]


In [ ]:
#Slicing in the 3-dimensional numpy array.
import numpy as np
a = np.array([[[12,13,14],
               [12,13,14],
               [12,13,14]]])
print(np.ndim(a))

3


In [ ]:
a = np.array([[1,2],
             [3,4]])
print(np.ndim(a))

2


In [ ]:
import numpy as np
a = np.array([[[12,3,4],
               [12,1,1],
               [12,3,1]]])

print(a[0][1])
print()
print(a[0][2])
print()
print(a[0][1])
print()
print(a[0][1][1])
print()
print(a[0][2][1])

[12  1  1]

[12  3  1]

[12  1  1]

1

3


In [1]:
import numpy as np

In [9]:
a = np.array([1,2,3,4,5])
print(a)

print(type(a))
print()
print(a.astype(int))
print()
print(len(a))
print()
print(a.shape)
print()
print(a.size)
print()
print(a.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>

[1 2 3 4 5]

5

(5,)

5

1


In [10]:
a = np.array([[1,2],[3,4]])
print(type(a))
print(a.ndim)
print(a.size)
print(a.dtype)
print(len(a))

<class 'numpy.ndarray'>
2
4
int64
2


In [11]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(arr1+arr2)

[[ 6  8]
 [10 12]]


In [18]:
b = np.concatenate([arr1,arr2])
print(len(b))
print(b)


4
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
print(b[3][1])

8


In [22]:
#spliting in array
arry = np.array([1,2,3,4,5,6])
print(np.array_split(arry,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [28]:
c = np.array([1,2,3,4,5,6,7,8,9])
d = np.array_split(c,5)

In [29]:
print(d[1])

[3 4]


In [34]:
a = np.array([1,2,3,4,5])
np.append(a,6)

array([1, 2, 3, 4, 5, 6])

In [35]:
np.insert(a,1,8)

array([1, 8, 2, 3, 4, 5])

In [38]:
np.delete(a,[1])

array([1, 3, 4, 5])

In [39]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [41]:
type(arr)

numpy.ndarray

In [42]:
arr.dtype

dtype('int64')

In [43]:
arr.ndim

1

In [44]:
len(arr)

8

In [45]:
arr.size

8

In [46]:
arr.shape

(8,)

In [47]:
a = np.array([[1,2],[3,4]])
a.shape

(2, 2)

In [48]:
arr = np.array([1,2,3,4,5,6])
np.append(arr,2)

array([1, 2, 3, 4, 5, 6, 2])

In [49]:
np.insert(arr,1,9)

array([1, 9, 2, 3, 4, 5, 6])

In [50]:
np.delete(arr,[1])

array([1, 3, 4, 5, 6])

In [51]:
print(arr.size)
print(arr.dtype)
print(arr.ndim)
print(arr.astype(int))
print(len(arr))

6
int64
1
[1 2 3 4 5 6]
6


In [52]:
hel = np.array([23,4,53,2,5,3,6,72])
print(np.sort(hel))

[ 2  3  4  5  6 23 53 72]


In [56]:
a = np.array([1,2,3,4])
np.where(a==2)

(array([1]),)

In [57]:
np.where(arr==4)

(array([3]),)

In [59]:
#filtering the array manually
arry = np.array([1,2,3,4])
fa = [True,False,True,False]
new = arry[fa]
print(new)

[1 3]


In [64]:
elem = np.array([1,2,3,4,5,6])
s = np.where(elem%2==0)
print(s)

(array([1, 3, 5]),)
