<a href="https://colab.research.google.com/github/Jatingpt/Only-for-practicing/blob/main/Only_Practice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#If else statement
marks = 89
if marks>85:
  print("You will go for a trip")
elif marks>75 and marks<85:
  print("You are a good student")
else:
  print("Needs improvement")

You will go for a trip


In [ ]:
def marks(num):
  if num>80:
    print("You will get a mobile")
  else:
    print("You really need an improvement.")

marks(89)


You will get a mobile


In [ ]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(1,11):
  if i == 5:
    print("You are dismissed")
  else:
    print(i)

1
2
3
4
You are dismissed
6
7
8
9
10


In [ ]:
def add(x,y):
  print(x+y)

add(3,4)

7


In [ ]:
a = ["Rohit", "Sohan", "Mohan", "Priya", "Greena"]
print(a)

['Rohit', 'Sohan', 'Mohan', 'Priya', 'Greena']


In [ ]:
print(a[1])

Sohan


In [ ]:
print(a[::-1])
print()
print(a[:2])
print(a[-3:-1])

['Greena', 'Priya', 'Mohan', 'Sohan', 'Rohit']

['Rohit', 'Sohan']
['Mohan', 'Priya']


In [ ]:
print(a[1:3])

['Sohan', 'Mohan']


In [ ]:
for i in range(1,101):
  if i%8==0 and i%12==0:
    print(i)

24
48
72
96


In [ ]:
#2*3.14*r
def area(r):
  print(2*3.14*r)

area(7)


43.96


In [ ]:
def rect_area(length,breath):
  print(length*breath)

rect_area(4,3)

12


In [ ]:
a = 1,2,3
b = "1,2,3"
a is b

False

In [ ]:
def mul(n):
  print(7*n)

mul(7)

49


In [ ]:
n = 7
for i in range(1,11):
  print(7*i)

7
14
21
28
35
42
49
56
63
70


In [ ]:
marks = 98
print("You are a good student") if marks>90 else print("You are an average student")

You are a good student


In [ ]:
a = 7
b = 1
while b<=10:
  print(a*b)
  b+=1

7
14
21
28
35
42
49
56
63
70


In [5]:
#Numpy stands for numeric python.
#deals with array.
#a library of python.
#numpy stores less memory.
#directly apply the math functions.
#performing faster.

import numpy as np

a = np.array([1,2,3,4])
print(a)

print(type(a))

print()

#Math operation in list
a = [1,2,3,4,5]
b = [1,2,3,4,5]
print(a+b)

print()


a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

print(a+b)

[1 2 3 4]
<class 'numpy.ndarray'>

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

[ 2  4  6  8 10]


In [9]:
arr = np.array([10, 23, 24, 25, 53, 53, 53])
print(arr)


print(arr[1])

[10 23 24 25 53 53 53]
23


In [18]:
#One-Dimensional Array.

a = np.array([3,4,5,2,3,6])
print(a)


#Slicing in one dimensional array.
a = np.array([3,4,5,2,3,6])
a[::-1]

[3 4 5 2 3 6]


array([6, 3, 2, 5, 4, 3])

In [26]:
#2-dimensional array.

a = np.array([[1,2],
             [3,4]])
print(a)

#slicing in 2-dimensional array.
a = np.array([[1,2],
             [3,4]])

print(a[1])

print()

print(a[0])

print()

print(a[0:1])

print()

print(a[0:2])

print()

print(a[1][1])

[[1 2]
 [3 4]]
[3 4]

[1 2]

[[1 2]]

[[1 2]
 [3 4]]

4


In [27]:
#3-dimensional array.

a = np.array([[[12,13,14],
               [12,13,14],
               [12,13,14]]])
print(a)

[[[12 13 14]
  [12 13 14]
  [12 13 14]]]


In [ ]:
a