<a href="https://colab.research.google.com/github/Jatingpt/Only-for-practicing/blob/main/Only_Practice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#If else statement
marks = 89
if marks>85:
  print("You will go for a trip")
elif marks>75 and marks<85:
  print("You are a good student")
else:
  print("Needs improvement")

You will go for a trip


In [ ]:
def marks(num):
  if num>80:
    print("You will get a mobile")
  else:
    print("You really need an improvement.")

marks(89)


You will get a mobile


In [ ]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(1,11):
  if i == 5:
    print("You are dismissed")
  else:
    print(i)

1
2
3
4
You are dismissed
6
7
8
9
10


In [ ]:
def add(x,y):
  print(x+y)

add(3,4)

7


In [ ]:
a = ["Rohit", "Sohan", "Mohan", "Priya", "Greena"]
print(a)

['Rohit', 'Sohan', 'Mohan', 'Priya', 'Greena']


In [ ]:
print(a[1])

Sohan


In [ ]:
print(a[::-1])
print()
print(a[:2])
print(a[-3:-1])

['Greena', 'Priya', 'Mohan', 'Sohan', 'Rohit']

['Rohit', 'Sohan']
['Mohan', 'Priya']


In [ ]:
print(a[1:3])

['Sohan', 'Mohan']


In [ ]:
for i in range(1,101):
  if i%8==0 and i%12==0:
    print(i)

24
48
72
96


In [ ]:
#2*3.14*r
def area(r):
  print(2*3.14*r)

area(7)


43.96


In [ ]:
def rect_area(length,breath):
  print(length*breath)

rect_area(4,3)

12


In [ ]:
a = 1,2,3
b = "1,2,3"
a is b

False

In [ ]:
def mul(n):
  print(7*n)

mul(7)

49


In [ ]:
n = 7
for i in range(1,11):
  print(7*i)

7
14
21
28
35
42
49
56
63
70


In [ ]:
marks = 98
print("You are a good student") if marks>90 else print("You are an average student")

You are a good student


In [ ]:
a = 7
b = 1
while b<=10:
  print(a*b)
  b+=1

7
14
21
28
35
42
49
56
63
70


In [ ]:
#Numpy stands for numeric python.
#deals with array.
#a library of python.
#numpy stores less memory.
#directly apply the math functions.
#performing faster.

import numpy as np

a = np.array([1,2,3,4])
print(a)

print(type(a))

print()

#Math operation in list
a = [1,2,3,4,5]
b = [1,2,3,4,5]
print(a+b)

print()


a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

print(a+b)

[1 2 3 4]
<class 'numpy.ndarray'>

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

[ 2  4  6  8 10]


In [ ]:
arr = np.array([10, 23, 24, 25, 53, 53, 53])
print(arr)


print(arr[1])

[10 23 24 25 53 53 53]
23


In [ ]:
#One-Dimensional Array.

a = np.array([3,4,5,2,3,6])
print(a)


#Slicing in one dimensional array.
a = np.array([3,4,5,2,3,6])
a[::-1]

[3 4 5 2 3 6]


array([6, 3, 2, 5, 4, 3])

In [ ]:
#2-dimensional array.

a = np.array([[1,2],
             [3,4]])
print(a)

#slicing in 2-dimensional array.
a = np.array([[1,2],
             [3,4]])

print(a[1])

print()

print(a[0])

print()

print(a[0:1])

print()

print(a[0:2])

print()

print(a[1][1])

[[1 2]
 [3 4]]
[3 4]

[1 2]

[[1 2]]

[[1 2]
 [3 4]]

4


In [ ]:
#3-dimensional array.

a = np.array([[[12,13,14],
               [12,13,14],
               [12,13,14]]])
print(a)

[[[12 13 14]
  [12 13 14]
  [12 13 14]]]


In [ ]:
#Slicing in the 3-dimensional numpy array.
import numpy as np
a = np.array([[[12,13,14],
               [12,13,14],
               [12,13,14]]])
print(np.ndim(a))

3


In [ ]:
a = np.array([[1,2],
             [3,4]])
print(np.ndim(a))

2


In [ ]:
import numpy as np
a = np.array([[[12,3,4],
               [12,1,1],
               [12,3,1]]])

print(a[0][1])
print()
print(a[0][2])
print()
print(a[0][1])
print()
print(a[0][1][1])
print()
print(a[0][2][1])

[12  1  1]

[12  3  1]

[12  1  1]

1

3


In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

print(type(a))
print()
print(a.astype(int))
print()
print(len(a))
print()
print(a.shape)
print()
print(a.size)
print()
print(a.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>

[1 2 3 4 5]

5

(5,)

5

1


In [ ]:
a = np.array([[1,2],[3,4]])
print(type(a))
print(a.ndim)
print(a.size)
print(a.dtype)
print(len(a))

<class 'numpy.ndarray'>
2
4
int64
2


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(arr1+arr2)

[[ 6  8]
 [10 12]]


In [ ]:
b = np.concatenate([arr1,arr2])
print(len(b))
print(b)


4
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(b[3][1])

8


In [ ]:
#spliting in array
arry = np.array([1,2,3,4,5,6])
print(np.array_split(arry,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
c = np.array([1,2,3,4,5,6,7,8,9])
d = np.array_split(c,5)

In [ ]:
print(d[1])

[3 4]


In [ ]:
a = np.array([1,2,3,4,5])
np.append(a,6)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.insert(a,1,8)

array([1, 8, 2, 3, 4, 5])

In [ ]:
np.delete(a,[1])

array([1, 3, 4, 5])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.ndim

1

In [ ]:
len(arr)

8

In [ ]:
arr.size

8

In [ ]:
arr.shape

(8,)

In [ ]:
a = np.array([[1,2],[3,4]])
a.shape

(2, 2)

In [ ]:
arr = np.array([1,2,3,4,5,6])
np.append(arr,2)

array([1, 2, 3, 4, 5, 6, 2])

In [ ]:
np.insert(arr,1,9)

array([1, 9, 2, 3, 4, 5, 6])

In [ ]:
np.delete(arr,[1])

array([1, 3, 4, 5, 6])

In [ ]:
print(arr.size)
print(arr.dtype)
print(arr.ndim)
print(arr.astype(int))
print(len(arr))

6
int64
1
[1 2 3 4 5 6]
6


In [ ]:
hel = np.array([23,4,53,2,5,3,6,72])
print(np.sort(hel))

[ 2  3  4  5  6 23 53 72]


In [ ]:
a = np.array([1,2,3,4])
np.where(a==2)

(array([1]),)

In [ ]:
np.where(arr==4)

(array([3]),)

In [ ]:
#filtering the array manually
arry = np.array([1,2,3,4])
fa = [True,False,True,False]
new = arry[fa]
print(new)

[1 3]


In [ ]:
elem = np.array([1,2,3,4,5,6])
s = np.where(elem%2==0)
print(s)

(array([1, 3, 5]),)


In [ ]:
#Creating a dictionary.
#Dictionary allows the user to write the data in the form of key and its values.
#The keys and values are separated by semicolon.
#We are using a curly brackets to create a dictionary.

employee = {"Name": "John", "Age": 34, "Gender": "Male"}
print(employee)

{'Name': 'John', 'Age': 34, 'Gender': 'Male'}


In [ ]:
print(employee["Name"])
print(employee["Age"])
print(employee["Gender"])

John
34
Male


In [ ]:
import pandas as pd

In [ ]:
employee = {"Name": ["John"], "Age": [34], "Gender": ["Male"]}
df = pd.DataFrame(employee)
df

Name  Age Gender
0  John   34   Male

In [ ]:
employee = {"name": ["john", "robin", "kailash"],
            "age": [23, 45, 56],
            "Gender": ["Male", "Male", "Male"]}
df = pd.DataFrame(employee)
df

name  age Gender
0     john   23   Male
1    robin   45   Male
2  kailash   56   Male

In [ ]:
for i in employee:
  print(i)

name
age
Gender


In [ ]:
for i in employee:
  print(employee[i])

['john', 'robin', 'kailash']
[23, 45, 56]
['Male', 'Male', 'Male']


In [ ]:
print(employee.items())

dict_items([('name', ['john', 'robin', 'kailash']), ('age', [23, 45, 56]), ('Gender', ['Male', 'Male', 'Male'])])


In [ ]:
print(employee["name"])

['john', 'robin', 'kailash']


In [ ]:
for x,y in employee.items():
  print(x,y)

name ['john', 'robin', 'kailash']
age [23, 45, 56]
Gender ['Male', 'Male', 'Male']


In [ ]:
for x in employee.values():
  print(x)

['john', 'robin', 'kailash']
[23, 45, 56]
['Male', 'Male', 'Male']


In [ ]:
for x in employee.keys():
  print(x)

name
age
Gender


In [ ]:
for i in range(1,202):
  if i%8==0 and i%12==0:
    print(i)

24
48
72
96
120
144
168
192


In [ ]:
def add(x,y):
  print(x+y)

add(2,3)

5


In [ ]:
def area_square(side):
  print(side*side)

area_square(4)

16


In [ ]:
for i in range(1,3):
  for j in range(1,5):
    print(j)

1
2
3
4
1
2
3
4


In [ ]:
#Sets = sets are the collections of unique datas.


In [ ]:
num1 = int(input("Enter a number here: "))
num2 = int(input("Enter another number here: "))
print(num1+num2)

Enter a number here: 8
Enter another number here: 8
16


In [ ]:
def add():
  num1 = int(input('Enter a number here: '))
  num2 = int(input('Enter another number here: '))
  print(num1+num2)

add()

Enter a number here: 7
Enter another number here: 7
14


In [ ]:
a = 1.23
b = int(a)
b

1

In [ ]:
type(b)

int

In [ ]:
name = input("Enter your name here: ")
age = int(input("Enter your age here: "))
roll_no = int(input("Enter your roll number here: "))
gender = input("Enter your gender here: ")

Enter your name here: Jasleen
Enter your age here: 23
Enter your roll number here: 21
Enter your gender here: Male


In [ ]:
#creating a nested dictionary.
dict = {1: {"Name": "John", "Age": 23, "Gender": "Male"},
        2: {"Name": "Preeti", "Age": 32, "Gender": "Female"}}
print(dict)

{1: {'Name': 'John', 'Age': 23, 'Gender': 'Male'}, 2: {'Name': 'Preeti', 'Age': 32, 'Gender': 'Female'}}


In [ ]:
print(dict[1])

{'Name': 'John', 'Age': 23, 'Gender': 'Male'}


In [ ]:
print(dict[1]["Name"])

John


In [ ]:
dict = {"Name": "John", "Age": 23, "Gender": "Male"}
print(dict)

{'Name': 'John', 'Age': 23, 'Gender': 'Male'}


In [ ]:
dict.keys()

dict_keys(['Name', 'Age', 'Gender'])

In [ ]:
dict.values()

dict_values(['John', 23, 'Male'])

In [ ]:
dict.get("Name")

'John'

In [ ]:
dict.items()

dict_items([('Name', 'John'), ('Age', 23), ('Gender', 'Male')])

In [ ]:
dict.setdefault("Age",24)

23

In [ ]:
print(dict["Age"])

23


In [ ]:
#Iteration in dictionary.
a = {1,2,3,4,5}
for i in a:
  print(i, end = " ")

1 2 3 4 5 

In [ ]:
dict = {"Name": "John", "Age": 23, "Gender": "Male"}

for x in dict.values():
  print(x)

John
23
Male


In [ ]:
for x in dict.keys():
  print(x)

Name
Age
Gender


In [ ]:
for x,y in dict.items():
  print(x,y)

Name John
Age 23
Gender Male


In [ ]:
#Sets
a = {"Ironman", "Thor", "Bahubali", "Superman"}


In [ ]:
a.pop()
print(a)

{'Bahubali', 'Superman', 'Thor'}


In [ ]:
a

{'Bahubali', 'Superman', 'Thor'}

In [ ]:
a.add("Batman")

In [ ]:
a

{'Bahubali', 'Batman', 'Superman', 'Thor'}

In [ ]:
a.remove("Superman")
print(a)

{'Bahubali', 'Thor', 'Batman'}


In [ ]:
a.discard("Thor")
a

{'Bahubali', 'Batman'}

In [ ]:
b = a.copy()
print(b)

{'Bahubali', 'Batman'}


In [ ]:
list1 = [1,2,3,4,5]
list1.append(6)
print(list1)

[1, 2, 3, 4, 5, 6]


In [ ]:
list1.remove(6)
print(list1)

[1, 2, 3, 4, 5]


In [ ]:
list1.pop()

5

In [ ]:
list1

[1, 2, 3, 4]

In [ ]:
list1.append(5)
print(list1)

[1, 2, 3, 4, 5, 5]


In [ ]:
list1.count(2)  #to count the occurence of the element in the list.

1

In [ ]:
list1.insert(1,7)
print(list1)

[1, 7, 7, 7, 7, 2, 3, 4, 5, 5]


In [ ]:
list1.pop(2)

7

In [ ]:
avengers = ["Spiderman", "Batman", "Krish"]
avengers[0]

'Spiderman'

In [ ]:
avengers.append("Hulk")
print(avengers)

['Spiderman', 'Batman', 'Krish', 'Hulk', 'Hulk']


In [ ]:
avengers.remove("Hulk")

In [ ]:
print(avengers)

['Spiderman', 'Batman', 'Krish', 'Hulk']


In [ ]:
#write a program to find a sum of all even numbers upto 50.
sum = 0
for i in range(1,51):
  if num % 2== 0:
    sum+=i
print("The sum of the even numbers upto 50 is ", sum)

The sum of the even numbers upto 50 is  1275


In [ ]:
a = ["Jammu", "New Delhi", "Mumbai"]
b = ["Madhya Pradesh", "Shimla"]
print(a+b)

['Jammu', 'New Delhi', 'Mumbai', 'Madhya Pradesh', 'Shimla']


In [ ]:
a = ["Jammu", "New Delhi", "Mumbai"]
b = ["Madhya Pradesh", "Shimla"]
print(a[1])
print()
print(a.index("Jammu"))

New Delhi

0
None


In [ ]:
a = ["Jammu", "New Delhi", "Mumbai"]
b = ["Madhya Pradesh", "Shimla"]
a.extend(b)
print(a)

['Jammu', 'New Delhi', 'Mumbai', 'Madhya Pradesh', 'Shimla']


In [ ]:
a.index("New Delhi")

1

In [ ]:
num = []
for num in range(1,51):
  if i%2==0:
    num=i
print(num)

100


In [ ]:
sum = 0
for i in range(1,51):
  if num % 2== 0:
    sum+=i
print(sum)

1275


In [ ]:
name = "Jasmine"
age = 23
address = "L-83 Border Street New Delhi-110033"
print(name)
print(age)
print(address)

Jasmine
23
L-83 Border Street New Delhi-110033


In [ ]:
a = "Rohit, Raj"
b = "Rani, Shalini"
a,b = b,a

In [ ]:
print(a)

Rani, Shalini


In [ ]:
a = 1.23
b = int(a)
print(b)

1


In [ ]:
name = input("Enter a name here: ")
age = int(input("Enter your age here: "))
gender = input("Enter your gender here: ")

Enter a name here: Hira Lal
Enter your age here: 43
Enter your gender here: Male


In [ ]:
user_input = int(input("Enter number here: "))
user_input = float(user_input)
print(user_input)

Enter number here: 3
3.0


In [ ]:
#Logical operators- AND, OR, NOT
3>2 and 2<4

True

In [ ]:
3>1 or 3<4

True

In [ ]:
not(3>1 or 3<1)

False

In [ ]:
not(1>2 and 0>1)

True

In [ ]:
a = 123
b = "123"
print(a is b)
print(a is not b)

False
True


In [ ]:
a = "aeiou"
"i" in a
"ei" in a

True

In [ ]:
amount = 45
if amount >50:
  print("He is a rich person")
elif amount > 40:
  print("He is going to be rice")
else:
  print("He is a happy person.")

He is going to be rice


In [ ]:
for i in range(1,5):
  if i == 2:
    continue
  else:
    print(i)

1
3
4


In [ ]:
for i in range(1,11):
  if i == 5:
    break
  else:
    print(i)

1
2
3
4


In [ ]:
x = lambda a,b,c: (a+b)*c
x(1,2,3)

9

In [ ]:
[i for i in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
count = 1
while count<=5:
  print(count)
  count+=1

1
2
3
4
5


In [ ]:

student = {"name": "Rashi", "age": 34, "roll no": 23, "gender": "female"}
for x in student:
  print(x)

name
age
roll no
gender


In [ ]:
student = {"name": "Rashi", "age": 34, "roll no": 23, "gender": "female"}
for x in student.items():
  print(x)

('name', 'Rashi')
('age', 34)
('roll no', 23)
('gender', 'female')


In [ ]:
student = {"name": "Rashi", "age": 34, "roll no": 23, "gender": "female"}
for x in student.values():
  print(x)


Rashi
34
23
female


In [ ]:
student = {"name": "Rashi", "age": 34, "roll no": 23, "gender": "female"}
for i in student.keys():
  print(i)

name
age
roll no
gender


In [ ]:
                                    ##Python from the start.
print("hello world")

hello world


In [ ]:
#data types in python- Text datatypes, integer dtypes, sequence dtypes, map dtypes,
#String, int, float, boolean, list, tuple, dictionary.

In [ ]:
#Taking the inputs from the user.
name = input("Enter a name here: ")
age = int(input("Enter the age here: "))
gender = input("Enter the gender here: ")

Enter a name here: Lara
Enter the age here: 23
Enter the gender here: Female


In [ ]:
#String- Whatever is comes under the inverted comma called string. It can be anything like int, float, boolean, text anything.

In [ ]:
#Typecasting- 2 Types of typecasting occurs
#1. Implicit- During the time of conversion or while performing the task python can change the dtypes by itself.
#2. Explicit- User has to change the dtypes from one type to another.

#Implicit
a = 123
b = 1.23
print(a+b)


#Explicit
a = 1.23
b = "123"
b = float(b)
print(a+b)

124.23
124.23


In [ ]:
                                                    #QUESTIONS
#Write a program to swap two variable.
a = "1,2,3"
b = "3,4,5"
a,b = b,a
print(a)
print(b)

#converting float into integer.
a = 1.23
b = int(a)
print(b)

3,4,5
1,2,3
1


In [ ]:
#Write the program to fill the id card for a student.
def student_details():
  input("Enter the name of the person: ")
  input("Enter the age of the person: ")
  input("Enter the roll number of the person: ")

student_details()

Enter the name of the person: Alisha
Enter the age of the person: 23
Enter the roll number of the person: 21


In [ ]:
#Take the user input as an integer and convert it into float.
                                          #Check because this function is running but not correctly
#def convert():
#  user_input = int(input("Enter the float number here: "))
#  user_input = float(user_input)

#convert()

user_input = int(input("Enter a number here: "))

converted_input = float(user_input)


print(converted_input)

Enter a number here: 3
3.0


In [ ]:
#Here we have total 6 types of operators-
#Arithmatic Operator - addition(+), substraction(-) etc
#Comparision Operator - "==", "<=" ">=" etc
#Identity Operator - "is" or "is not"
#Membership Operator- "in" or "not in"
#Logical Operator- AND, OR, NOT
#Assignment Operator-

In [ ]:
sugar = 350
if sugar>400:
  print("You will be in danger soon.")
elif sugar> 300 and sugar<=400:
  print("You should immidiatly take the prevention")
else:
  print("Do excercise daily.")

You should immidiatly take the prevention


In [ ]:
marks = 68
print("You will go for picnic") if marks>70 else print("Go and read again then come for exams")

Go and read again then come for exams


In [ ]:
x = lambda a,b,c: (a+b)*c
x(3,3,5)

30

In [ ]:
#Taking a variable as an integer and converting it into float.
user_input = int(input("Enter a number here: "))

converted_input = float(user_input)


print(converted_input)

Enter a number here: 2
2.0


In [ ]:
a = "1,3,4"
b = [2,3,4]
print(a is b)

print(a is not b)

False
True


In [ ]:
marks = 97
print("You will definitely win the prize") if marks > 89 else print("good luck")

You will definitely win the prize


In [ ]:
sum = 0
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [ ]:
#List Comprehension
#Square of a number till 10 by using list comprehension.

square = [x**2 for x in range(1,11)]
print(square)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
even_number = [x for x in range(1,51) if x%2==0]
print(even_number)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


In [ ]:
pos_num = int(input("Enter a number here: "))
def pos_num():
  if pos_num >=0:
    print("It is a positive number")
  else:
    print("It is a negative number")

Enter a number here: 4


In [ ]:
#writing a program to check whether a number is positive or negative.
num = int(input("Enter a number here: "))
if num >= 0:
  print("It is a positive number")
else:
  print("It is a negative number")

Enter a number here: 3
It is a positive number


In [ ]:
#write a program to check a number is odd or even.
num = int(input("Enter any number here: "))
if num % 2 == 0:
  print("It is a even number ")
else:
  print("It is a odd number")

Enter any number here: 3
It is a odd number


In [ ]:
#write a program to check area calculator.

##                area calculator
#press 1 to find the area of a square.
#press 2 to find the area of the rectangle.

num = int(input("Enter a number here: "))
if num == 1:
  side = float(input("Enter the side of the square: "))
  area_sq = side*side
  print(area_sq)
elif num == 2:
  length = float(input("Enter the length of the rectangle: "))
  breath = float(input("Enter the breath of the rectangle: "))
  area_rect = length*breath
  print(area_rect)
else:
  print("Invalid Input")

Enter a number here: 2
Enter the length of the rectangle: 6
Enter the breath of the rectangle: 6
36.0


In [ ]:
#write a program to check whether the pass letter is a vowel of consoment.
letter = "d"
if letter in "aeiou" or letter in "AEIOU":            #we are using membership operator here.
  print("It is a vowel")
else:
  print("It is a consonent")

It is a consonent


In [ ]:
#write a program to check if a number is a single digit number or double digit number.
number = int(input("Enter a number here: "))
if number >= 0 and number <= 9:
  print("It is a single digit number.")
elif number >= 10 and number <= 99:
  print("It is a double digit number.")
else:
  print("INVALID INPUT")

Enter a number here: 88
It is a double digit number.


In [ ]:
#For Loop.
for i in range(1,11):
  print(f"The square of the {i} is", i*i)

The square of the 1 is 1
The square of the 2 is 4
The square of the 3 is 9
The square of the 4 is 16
The square of the 5 is 25
The square of the 6 is 36
The square of the 7 is 49
The square of the 8 is 64
The square of the 9 is 81
The square of the 10 is 100


In [ ]:
import pandas as pd

In [ ]:
#Some of the concepts of pandas.
data = {"Name": ["Naman", "Jasmine", "Kritisha"],
        "Age": [23, 43, 35],
        "Gender": ["Female", "Female", "Female"]}
df = pd.DataFrame(data)
df

Name  Age  Gender
0     Naman   23  Female
1   Jasmine   43  Female
2  Kritisha   35  Female

In [ ]:
from google.colab import drive
drive.mount("/content/drive/")

Mounted at /content/drive/


In [ ]:
path = "/content/sample_data/california_housing_test.csv"
data = pd.read_csv(path)
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [ ]:
data.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0

In [ ]:
data["housing_median_age"].mean()

28.845333333333333

In [ ]:
data.duplicated().sum()

0

In [ ]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


In [ ]:
print(data["total_rooms"].duplicated().sum())

785


In [ ]:
print(data.drop_duplicates("total_rooms"))

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2987    -121.97     37.29                25.0       4096.0           743.0   
2989    -122.02     37.60                32.0       1295.0           295.0   
2991    -117.17     34.28                13.0       4867.0           718.0   
2992    -122.33     37.39                52.0        573.0           102.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   

      population  households  median_income  median_house_value

In [ ]:
data.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
employee = {"Name": ["Bishwas", "Roy", "Tom", "Lisa", "Lovely", "Rashmi"],
            "Age": [23, 34, 33, 23, 29, 32],
            "Gender": ["Female", "Male", "Male", "Female", "Female", None]}

In [ ]:
df = pd.DataFrame(employee)
df

Name  Age  Gender
0  Bishwas   23  Female
1      Roy   34    Male
2      Tom   33    Male
3     Lisa   23  Female
4   Lovely   29  Female
5   Rashmi   32    None

In [ ]:
df.duplicated("Age")

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

In [ ]:
df.drop_duplicates("Age")

Name  Age  Gender
0  Bishwas   23  Female
1      Roy   34    Male
2      Tom   33    Male
4   Lovely   29  Female
5   Rashmi   32    None

In [ ]:
df.fillna("Female")

Name  Age  Gender
0  Bishwas   23  Female
1      Roy   34    Male
2      Tom   33    Male
3     Lisa   23  Female
4   Lovely   29  Female
5   Rashmi   32  Female

In [ ]:
df["Gender"].fillna("Female", inplace=True)

In [ ]:
df

Name  Age  Gender
0  Bishwas   23  Female
1      Roy   34    Male
2      Tom   33    Male
3     Lisa   23  Female
4   Lovely   29  Female
5   Rashmi   32  Female

In [ ]:
df.loc[df["Gender"] == "Female"]

Name  Age  Gender
0  Bishwas   23  Female
3     Lisa   23  Female
4   Lovely   29  Female
5   Rashmi   32  Female

In [ ]:
#write a program to swap two variables.
a = 12
b = 13
temp = 12
a = b
b = temp
print(a)
print()
print(b)

13

12


In [ ]:
num = int(input("Enter a integer here: "))
num = float(num)
print(num)
print(type(num))

Enter a integer here: 4
4.0
<class 'float'>


In [ ]:
#logical operator
2>4 and 3>1

False

In [ ]:
a = 123
b = 1.23
print(a is b)
print(a is not b)

False
True


In [ ]:
a = "aeiou"
print("a" not in a)
print("a" in a)

False
True


In [ ]:
#if statement
marks = 84
if marks > 80:
  print("You will win the award.")

You will win the award.


In [ ]:
#short hand if statement.
marks = 80
if marks > 70: print("Very well")

Very well


In [ ]:
#short hand if-else statement.
marks = 67
print("You are a good student") if marks > 85 else print("You really need to imporve yourself.")

You really need to imporve yourself.


In [ ]:
#write a program to check a number is positive.
num = int(input("Enter a number here "))
if num > 0:
  print("It is a positive number.")
else:
  print("It is a negative number")

Enter a number here 9
It is a positive number.


In [ ]:
number = int(input("Enter a number here: "))
if number % 2 == 0:
  print ("We got an even number here as an input.")
else:
  print("Sadly, we got an odd number.")

Enter a number here: 7
Sadly, we got an odd number.


In [ ]:
#write a program to check whether the number is a vowel or not.
letter = input("Enter any letter here: ")
if letter in "aeiou" and letter in "AEIOU":
  print("It is a vowel")
else:
  print("It is a consonent or not vowel.")

Enter any letter here: K
It is a consonent or not vowel.


In [ ]:
#To check the number of digits.
num = int(input("Enter number here: "))
if num >= 0 and num < 9:
  print("Single digit number.")
elif num >= 10 and num <= 99:
  print("Double digits!!")
elif num >=100 and num <= 999:
  print("Three digits number.")
else:
  print("Invalid Input!!")

Enter number here: 888
Three digits number.


In [ ]:
#for loop
for i in range(1,6):
  print(i)

1
2
3
4
5


In [ ]:
for i in range(1,6):
  if i == 3:
    continue
  else:
    print(i)

1
2
4
5


In [ ]:
for i in range(1,11):
  if i == 5:
    break

In [ ]:
for i in range(1,23):
  if i == 5:
    break
  else:
    print(i)

1
2
3
4


In [ ]:
#while loop
n = 1
while n <= 5:
  print(n)
  n+=1

1
2
3
4
5


In [ ]:
#table of 5 using while loop.
n = 1
a = 5
while n<=10:
  print(a, "x", n,"=",a*n)
  n+=1

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [ ]:
n = 7
for i in range(1,11):
  print(n*i)


7
14
21
28
35
42
49
56
63
70


In [ ]:
def count_upto(n):
  count = 1
  while count <= 10:
    yield count
    count += 1

counter = count_upto(10)

for i in counter:
  print(i)



1
2
3
4
5
6
7
8
9
10


In [ ]:
#What are generators?
#Generators are the special type of iterables that generates the value without storing the memory.
#one of the major advantages of this generators is it is memory efficient.

def count_up_to(n):
  count = 1
  while count<=5:
    yield count
    count+=1

counter = count_up_to(5)

for number in counter:
  print(number)

In [ ]:
#again
def count_up_to(n):
  count = 1
  while count<=10:
    yield count
    count+=1
counter = count_up_to(10)

for i in counter:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
#What is exceptional handling in python.
#exceptional handling in python is used to prevent crashes or to avoid erros.
#We use try, except and finally to handle the exception.

try:
  num = int(input("Enter a number here: "))
  print(10/num)
except ZeroDivisionError:
  print("Cannot divided by zero!")
except ValueError:
  print("Invalid Input!")
else:
  print("Division Successful!")
finally:
  print("Program Completed")

Enter a number here: -
Invalid Input!
Program Completed


In [ ]:
#What is decorator?
#A decorator is used to modify or extend the behaviour of the function without changing it's original structure.
#Advantages- Enhance functionality, Reusable.

In [ ]:
#lambda function.
x = lambda a,b,c: (a+b)*c
print(x(1,2,3))

9


In [ ]:
def count_upto(n):
  count = 1
  while count<=5:
    yield count
    count+=1

counter = count_upto(5)

for i in counter:
  print(i)

1
2
3
4
5


In [ ]:
#
def count_upto(n):
  count = 1
  while count <= 5:
    yield count
    count += 1

counter = count_upto(5)

for i in counter:
  print(i)

1
2
3
4
5


In [ ]:
#lambda function.
x = lambda a,b,c: (a+b)*c
print(x(1,2,3))

9


In [ ]:
import pandas as pd

In [ ]:
df = {"Name": ["Hari", "Priya", "Rathiram", "July"],
      "Age": [24, 35, 23, 25],
      "Gender": ["Male", "Female", "Male", "Female"]}
df = pd.DataFrame(df)
df

Name  Age  Gender
0      Hari   24    Male
1     Priya   35  Female
2  Rathiram   23    Male
3      July   25  Female

In [ ]:
age = df.loc[df["Age"]>24]             #loc method used to access the details of the data over a certain condition.

#age

print(df)

       Name  Age  Gender
0      Hari   24    Male
1     Priya   35  Female
2  Rathiram   23    Male
3      July   25  Female


In [ ]:
df.loc[df["Gender"] == "Male"]

Name  Age Gender
0      Hari   24   Male
2  Rathiram   23   Male

In [ ]:
df.loc[df["Gender"] == "Female"]

Name  Age  Gender
1  Priya   35  Female
3   July   25  Female

In [ ]:
print(df.iloc[0:3])  #iloc stands for index location.

       Name  Age  Gender
0      Hari   24    Male
1     Priya   35  Female
2  Rathiram   23    Male


In [ ]:
#Column transformation.
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"]}

df = pd.DataFrame(data)
df

First Name Last Name  Age  Gender
0     Rohini   Kashyap   23  Female
1        Raj     Kumar   45    Male
2       Rani       Raj   35  Female
3      Aasma     Sinha   29  Female

In [ ]:
df["FullName"] = df["First Name"] + " " + df["Last Name"]
df

First Name Last Name  Age  Gender        FullName
0     Rohini   Kashyap   23  Female  Rohini Kashyap
1        Raj     Kumar   45    Male       Raj Kumar
2       Rani       Raj   35  Female        Rani Raj
3      Aasma     Sinha   29  Female     Aasma Sinha

In [ ]:
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"],
        "Salary": [45000, 49000, 56000, 34000]}

df = pd.DataFrame(data)
df

First Name Last Name  Age  Gender  Salary
0     Rohini   Kashyap   23  Female   45000
1        Raj     Kumar   45    Male   49000
2       Rani       Raj   35  Female   56000
3      Aasma     Sinha   29  Female   34000

In [ ]:
df.loc[(df["Salary"] <35000), "GetsBonus"] = "Bonus"

df.loc[(df["Salary"]> 35000), "GetsBonus"] = "No Bonus"

df

First Name Last Name  Age  Gender  Salary GetsBonus
0     Rohini   Kashyap   23  Female   45000  No Bonus
1        Raj     Kumar   45    Male   49000  No Bonus
2       Rani       Raj   35  Female   56000  No Bonus
3      Aasma     Sinha   29  Female   34000     Bonus

In [ ]:
#GroupBy in Pandas.
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"],
        "Salary": [45000, 49000, 56000, 34000],
        "City": ["New Delhi", "Mumbai", "Hydrabad", "New Delhi"]}

df = pd.DataFrame(data)
df

First Name Last Name  Age  Gender  Salary       City
0     Rohini   Kashyap   23  Female   45000  New Delhi
1        Raj     Kumar   45    Male   49000     Mumbai
2       Rani       Raj   35  Female   56000   Hydrabad
3      Aasma     Sinha   29  Female   34000  New Delhi

In [ ]:
gp = df.groupby("City").size()
print(gp)


City
Hydrabad     1
Mumbai       1
New Delhi    2
dtype: int64


In [ ]:
import pandas as pd

In [ ]:
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"]}

df = pd.DataFrame(data)
df

First Name Last Name  Age  Gender
0     Rohini   Kashyap   23  Female
1        Raj     Kumar   45    Male
2       Rani       Raj   35  Female
3      Aasma     Sinha   29  Female

In [ ]:
df["Full Name"] = df["First Name"] + " " + df["Last Name"]

In [ ]:
df


First Name Last Name  Age  Gender       Full Name
0     Rohini   Kashyap   23  Female  Rohini Kashyap
1        Raj     Kumar   45    Male       Raj Kumar
2       Rani       Raj   35  Female        Rani Raj
3      Aasma     Sinha   29  Female     Aasma Sinha

In [ ]:
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"],
        "Salary": [45000, 49000, 56000, 34000]}

df = pd.DataFrame(data)
df

First Name Last Name  Age  Gender  Salary
0     Rohini   Kashyap   23  Female   45000
1        Raj     Kumar   45    Male   49000
2       Rani       Raj   35  Female   56000
3      Aasma     Sinha   29  Female   34000

In [ ]:
df.loc[(df["Salary"]> 35000), "Gets Bonus"] = "Bonus"
df.loc[(df["Salary"]< 34500), "Gets Bonus"] = "No Bonus"

In [ ]:
df

First Name Last Name  Age  Gender  Salary Gets Bonus
0     Rohini   Kashyap   23  Female   45000      Bonus
1        Raj     Kumar   45    Male   49000      Bonus
2       Rani       Raj   35  Female   56000      Bonus
3      Aasma     Sinha   29  Female   34000   No Bonus

In [ ]:
#GroupBy in Pandas.
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"],
        "Salary": [45000, 49000, 56000, 34000],
        "City": ["New Delhi", "Mumbai", "Hydrabad", "New Delhi"]}

df = pd.DataFrame(data)
df

First Name Last Name  Age  Gender  Salary       City
0     Rohini   Kashyap   23  Female   45000  New Delhi
1        Raj     Kumar   45    Male   49000     Mumbai
2       Rani       Raj   35  Female   56000   Hydrabad
3      Aasma     Sinha   29  Female   34000  New Delhi

In [ ]:
gp = df.groupby("City").size()
gp

City
Hydrabad     1
Mumbai       1
New Delhi    2
dtype: int64

In [ ]:
data = [
    {"category": "fruit", "item": "apple", "price": 1.2},
    {"category": "fruit", "item": "banana", "price": 0.5},
    {"category": "vegetable", "item": "carrot", "price": 0.7},
    {"category": "vegetable", "ite,m": "broccoli", "price": 1.0},
    {"category": "fruit", "item": "orange", "price": 1.3}
]

df = pd.DataFrame(data)
df

category      item  price
0      fruit     apple    1.2
1      fruit    banana    0.5
2  vegetable    carrot    0.7
3  vegetable  broccoli    1.0
4      fruit    orange    1.3

In [ ]:
df.groupby("category").sum()

item  price
category                           
fruit      applebananaorange    3.0
vegetable     carrotbroccoli    1.7

In [ ]:
name = ["Rohini", "Raj", "Rani", "Aasma"]
index = name.index("Rohini")
name[index] = "Ritika"
print(name)

['Ritika', 'Raj', 'Rani', 'Aasma']


In [ ]:
name = ["Rohini", "Raj", "Rani", "Aasma"]

# Find the index of "Raj" and replace it with "Rohini"
index = name.index("Raj")  # This finds the index of "Raj"
name[index] = "Rohini"     # Replace the element at that index

print(name)

In [ ]:
names = "Rani, Priya, Preeti, Priyanshi"
names.replace("Rani","Ishita")
print(names)

Rani, Priya, Preeti, Priyanshi


In [ ]:
name = ["Rohini", "Raj", "Rani", "Aasma"]
name.pop()
print(name)

['Rohini', 'Raj', 'Rani']


In [ ]:
for i in range(1,11):
  if i == 5:
    continue
  else:
    print(i)

1
2
3
4
6
7
8
9
10


In [ ]:
#not working
for i in range(1,11):
  if i == 5:
    continue
print(i)

10


In [ ]:
for i in range(1,11):
  if i == 5:
    break
  else:
    print(i)

1
2
3
4


In [ ]:
                                                            #String

#Here all the functions and methods used in a string.
#capitalize(), lower(), upper(), casefold(), title(), len(), type(),
#aggeregate func and search functions - min, max, count, rfind, find, index, rindex
#trimming- split, strip, partition, join()
#replacing- replace, translate(),
#endoging = format,
#basic operations - len, sorted, max, min, str, reversed, enumerate().

In [ ]:
name = "bunty"
a = "my name is {}"
print(a.format(name))

my name is bunty


In [ ]:
#to add two different strings.
first_name = "Dipak"
last_name = "Roy"
full_name = first_name+ " " +last_name
print(full_name)

Dipak Roy


In [ ]:
name = "Jonny"
b = name.format()
print("my name is {}, so, you should give respect.")

my name is {}, so, you should give respect.


In [ ]:
string_c = "i am requesting to the god, for my placement as soon as possible.     "
print(string_c.split())
print(string_c.strip())
print(string_c.replace("requesting", "begging"))
print(string_c.rfind("a"))      #it will provide the the place of the last element in the last.

['i', 'am', 'requesting', 'to', 'the', 'god,', 'for', 'my', 'placement', 'as', 'soon', 'as', 'possible.']
i am requesting to the god, for my placement as soon as possible.
i am begging to the god, for my placement as soon as possible.     
53


In [ ]:
string_b = "i wish i could change my job as soon as possible."
print(string_b.capitalize())
print(string_b.upper())
print(string_b.casefold())
print(string_b.lower())

I wish i could change my job as soon as possible.
I WISH I COULD CHANGE MY JOB AS SOON AS POSSIBLE.
i wish i could change my job as soon as possible.
i wish i could change my job as soon as possible.


In [ ]:
a_str = "I am ready to change my domain."
print(len(a_str))
print(type(a_str))
print(a_str.find("to"))
print(a_str.index("my"))
print(a_str.count("a"))  #print(count(a_str)) here i did before and it was wrong.

31
<class 'str'>
11
21
4


In [ ]:
                                                            #Lists
#all functions and methods used in a list


#Add/modify - append, extend, insert.
#for remove- remove, pop, clear.
#search - index, count                   NOTES- find method is not in the list while it is working in string.
#reorder- sort, reverse                  #NOTES- sort function is not working in terms of lists.
#copy - copy()

#basic functions- len, sorted, max, sum, all, reversed, enumerate, zip(*lists).

In [ ]:
list1 = [1, 2, 3, 2, 5, "Hello", "rohit"]
print(list1.append("Vikas"))
print(list1)

print(list1.extend("123"))
print(list1)

print(list1.insert(0,"Hooda"))
print(list1)

None
[1, 2, 3, 2, 5, 'Hello', 'rohit', 'Vikas']
None
[1, 2, 3, 2, 5, 'Hello', 'rohit', 'Vikas', '1', '2', '3']
None
['Hooda', 1, 2, 3, 2, 5, 'Hello', 'rohit', 'Vikas', '1', '2', '3']


In [ ]:
list1 = [1, 2, 3, 2, 5, "Hello", "rohit"]

# Append "Vikas" to the list
list1.append("Vikas")
print("After append:", list1)

# Add "Brother" as a single element
list1.append("Brother")  # Use append instead of extend
print("After appending 'Brother':", list1)

# Find the index of 5
index_of_5 = list1.index(5)
print("Index of 5:", index_of_5)

# Insert "Professional" at the beginning
list1.insert(0, "Professional")
print("After inserting 'Professional':", list1)

In [ ]:
name = "Sohit"
a = name.format()
print("my name is { }")


name = "Vijay"
a = "my name is {}"
print(a.format(name))

my name is { }
my name is Vijay


In [ ]:
name = "queen"
a = "my name is {}"
print(a.format(name))

my name is queen


In [ ]:
def add(x,y):
  print("The addition of these two numbers is", x+y)
add(2,3)

The addition of these two numbers is 5


In [ ]:
def marks(num):
  if num >=90:
    print("You are a brilliant student.")
  elif num>=80 and num <=89:
    print("You will be a brilliant student someday.")
  else:
    print("You need to improve yourself.")
    print("Thank you")

marks(85)

You will be a brilliant student someday.


In [ ]:
x = lambda a,b,c: (a+b)*c
x(1,2,3)


9

In [ ]:
for i in range(1,11):
  if i == 3:
    print("Skip this song.")
  else:
    print(i)

1
2
Skip this song.
4
5
6
7
8
9
10


In [ ]:
a = ["Ramayana", "Mahabharat", "Shiv Puran", "Bala Ji Maharaj"]
for i in a:
  print(i, end = " ")

Ramayana Mahabharat Shiv Puran Bala Ji Maharaj 

In [ ]:
dic = {"name": ["Ramya", "Rani", "Rosy", "Rachel"],
        "age": [23, 24, 25, 32],
        "salary": [23000, 30000, 42000, 35000]}

#for i in dic:
#  print(i)

#for i in dic:
#  print(dic[i])

#for i in dic:
#  print(dic[i][1])

Rani Rani Rani 

In [ ]:
dic = {"name": ["Ramya", "Rani", "Rosy", "Rachel"],
        "age": [23, 24, 25, 32],
        "salary": [23000, 30000, 42000, 35000]}

dic["name"][1]

'Rani'

In [ ]:
sets = {"hulk", "thor", "superman", "spiderman"}
sets.add("Batman")
sets

{'Batman', 'hulk', 'spiderman', 'superman', 'thor'}

In [ ]:
import pandas as pd
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"],
        "Salary": [45000, 49000, 56000, 34000],
        "City": ["New Delhi", "Mumbai", "Hydrabad", "New Delhi"]}

df = pd.DataFrame(data)


gp = df.groupby(["City", "Gender"])
print(gp)


                  First Name  Last Name  Age  Salary
City      Gender                                    
Hydrabad  Female           1          1    1       1
Mumbai    Male             1          1    1       1
New Delhi Female           2          2    2       2


In [ ]:
import pandas as pd

data = {
    "First Name": ["Rohini", "Raj", "Rani", "Aasma"],
    "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
    "Age": [23, 45, 35, 29],
    "Gender": ["Female", "Male", "Female", "Female"],
    "Salary": [45000, 49000, 56000, 34000],
    "City": ["New Delhi", "Mumbai", "Hydrabad", "New Delhi"]
}

df = pd.DataFrame(data)

# Corrected groupby code
gp = df.groupby(["City", "Gender"])
print(gp)

In [ ]:
gb = df.groupby("City").size()
gb

City
Hydrabad     1
Mumbai       1
New Delhi    2
dtype: int64

In [3]:
#Generators = It is a special types of iterables which generates the values without storing the memory.

def count_upto(n):
  count = 1
  while count < 5:
    yield count
    count += 1
counter = count_upto(5)

for i in counter:
  print(i)

1
2
3
4


In [10]:
#Shallow copy- A shallow copy is the copy of an object that stores the reference of the original element.
#A shallow copy is the copy of an object which stores the reference of the original element.
import copy

original = [1,[2,3],4]
shallow = copy.copy(original)
original[1][0] = 99
print("original:", original)
print("shallow copy:", shallow)

original: [1, [99, 3], 4]
shallow copy: [1, [99, 3], 4]


In [12]:
#Deep Copy-  A deep copy creates a completely independent copy of the object and all the object inside it.
original = [1,[2,3],4]
deep = copy.deepcopy(original)
original[1][0] = 99
print("original:", original)
print("Deep Copy:", deep)

original: [1, [99, 3], 4]
Deep Copy: [1, [2, 3], 4]
