<a href="https://colab.research.google.com/github/Jatingpt/Only-for-practicing/blob/main/Only_Practice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data Analysis- Data Analysis is the science of analyzing data and to find trends of answers and questions.
#Typecasting-
#Implicit typecasting
a = 123
b = 1.23
c = a + b
print(c)
print(type(c))

a = "123"
b = 123
a = int(a)
c = a + b
print(c)
print(type(c))

124.23
<class 'float'>
246
<class 'int'>


In [ ]:
#To display person's name, age and address.
name = "Vilas"
age = 23
address = "S- Vidhya Nagar Mumbai-892200"
print(name)
print(age)
print(address)

print()

#Swapping two variables.
a = 12
b = 34
a,b = b,a
print(a)
print(b)

print()

#Convert float into integer.
a = 1.23
print(int(a))

print()

#write a program to take details from a student for Id-Card.
name = input("Enter the name here: ")
age = int(input(("Enter the age of the student: ")))
classs = input("Enter the class of the student: ")

print(name)
print(age)
print(classs)

print()

#take input from the user as integer and convert it into float.
user = int(input("Enter any integer here: "))
user = float(user)
print("The converted input in float is:", user)

Vilas
23
S- Vidhya Nagar Mumbai-892200

34
12

1

Enter the name here: Honey Singh
Enter the age of the student: 45
Enter the class of the student: FDK
Honey Singh
45
FDK

Enter any integer here: 50
The converted input in float is: 50.0


In [ ]:
#Operators- The whole equation is called operators while the elements which we are using in this equation are called Operands.
#Total 6 types of operators that we are going to use-
# 1. Arithmatic, Logical, Comparision, Identity, Membership, Assignment, Bitwise.

#Logical Operators-

34 > 45 or 45 > 34

34 > 45 and 45 > 34

not(34 > 45 and 45 > 34)

#Identity operator.
a = "123"
b = 123
print(a is b)
print(a is not b)

#Membership Operator.
a = "1223455"
print("1" in a)

#Conditional Statements-

#if, if-else, if-elif-else, nested conditional statement, short-hand if and short-hand if-else statement.

marks = 79
if marks > 80:
  print("Good Score")
print("Need Improvement.")

if marks > 70:
  print("A nice scoree.")
else:
  print("Needs improvement.")

#Nested Statement.

marks = 72
if marks >= 90:
  print("Excellent")
  if marks >= 70 and marks <= 89:
    print("Good Work")
else:
  print("Will Check the copy.")

False
True
True
Need Improvement.
A nice scoree.
Will Check the copy.


In [ ]:
marks = 89
print("Good Work") if marks > 90 else print("Needs Improvement.")

mark = 87
if mark > 78: print("Nice Brother.")

Needs Improvement.
Nice Brother.


In [52]:
#Write a program to check whether a number is positive or negative.
num = int(input("Enter any number here: "))
if num >= 1:
  print("This is a positive number.")
else:
  print("This is a negative number.")

#Write a program to check whether a number is odd or even.
num = int(input("Enter any number here: "))
if num % 2 == 0:
  print("It is a even number.")
else:
  print("It is a odd number.")

#Write a program to create area calculator.

#Write a program to check whether the passed letter is a vowel or not.
def vow(n):
  if n in "AEIOUaeiou":
    print("It is a vowel")
  else:
    print("Not a vowel")
vow("p")

Enter any number here: 8
This is a positive number.
Enter any number here: 9
It is a odd number.
Not a vowel


In [ ]:
#If else statement
marks = 89
if marks>85:
  print("You will go for a trip")
elif marks>75 and marks<85:
  print("You are a good student")
else:
  print("Needs improvement")

You will go for a trip


In [ ]:
#palindrome
num = input("Enter anything here: ")
if num == num[::-1]:
  print("It is a palindrome")
else:
  print("Not a palindrome.")

Enter anything here: 21
Not a palindrome.


In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c
fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [ ]:
def fact(n):
  if n == 1:
    return n
  else:
    return n*fact(n-1)
fact(5)

120

In [ ]:
#To find the factorial of any number.
def fact(n):
  if n == 1:
    return n
  else :
    return n*fact(n-1)
fact(5)

120

In [ ]:
#to find the palindrome of any number.
n = input("Enter anything here: ")
if n == n[::-1]:
  print("It is a palindrome.")
else:
  print("Not a palindrome.")

Enter anything here: 23
Not a palindrome.


In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a, end = " ")
    c = a + b
    a = b
    b = c
fibonacci(10)

0 1 1 2 3 5 8 13 21 34 

In [ ]:
#To find the factorial of any number.
def fact(n):
  if n == 1:
    return n
  else:
    return n*fact(n-1)
fact(5)

120

In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a, end = " ")
    c = a + b
    a = b
    b = c
fibonacci(10)

0 1 1 2 3 5 8 13 21 34 

In [ ]:
#to find the palindrome of any number.
n = input("Enter anything here: ")
if n == n[::-1]:
  print("It is a palindrome.")
else:
  print("Not a palindrome.")

Enter anything here: 121
It is a palindrome.


In [ ]:
#Let's create an area calculator.
print("Press 1 to find the area of the rectangle: ")
print("Press 2 to find the area of the square: ")
print("Press 3 to find the area of the circle: ")
area_ = int(input("Enter the number between 1 and 3 to find the area: "))
if area_ == 1:
  length = float(input("Enter the length of the rectangle: "))
  width = float(input("Enter the width of the rectangle: "))
  area_rect = length*width
  print(area_rect)
elif area_ == 2:
  side = float(input("Enter the side of the square"))
  area_square = side*side
  print(area_square)
elif area_ == 3:
  radius = float(input("Enter the radius of the square: "))
  area_circle = (2*3.14*radius)
  print(area_circle)
else:
  print("INVALID INPUT!!!!")


Press 1 to find the area of the rectangle: 
Press 2 to find the area of the square: 
Press 3 to find the area of the circle: 
Enter the number between 1 and 3 to find the area: 2
Enter the side of the square8
64.0


In [ ]:

def fact(n):
  if n == 1:
    return n
  else:
    return n*fact(n-1)
fact(5)

120

In [ ]:
n = input("Enter anything here: ")
if n == n[::-1]:
  print("It is a palindrome.")
else:
  print("Not a palindrome.")

Enter anything here: 121
It is a palindrome.


In [ ]:
for i in range(1,11):
  if i == 3:
    print("Skip this part")
  else:
    print(i)

1
2
Skip this part
4
5
6
7
8
9
10


In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a, end = " ")
    c = a + b
    a = b
    b = c
fibonacci(10)

0 1 1 2 3 5 8 13 21 34 

In [ ]:
#palindrome
n = input("Enter anything here: ")
if n == n[::-1]:
  print("It is a palindrome.")
else:
  print("Not a palindrome")

Enter anything here: 21
Not a palindrome


In [ ]:
def fact(n):
  if n == 1:
    return n
  else:
    return n*fact(n-1)
fact(5)

120

In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c
fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [ ]:
#write a program to check whether the number is a vowel or consonent.
vow = input('Enter anything here: ')
if vow in "aeiouAEIOU":
  print("It is a vowel.")
else:
  print("Not a vowel.")

Enter anything here: i
It is a vowel.


In [ ]:
n = 0
while n < 5:
  print(n)
  n += 1

0
1
2
3
4


In [ ]:
vow = input("Enter any letter here: ")
if vow in "aeiouAEIOU":
  print("It is a vowel.")
else:
  print("Not a vowel.")

Enter any letter here: t
Not a vowel.


In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c
fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [ ]:
def fact(n):
  if n == 1:
    return n
  else:
    return n*fact(n-1)
fact(5)

120

In [ ]:
#creating a table by using while loop.
n = 1
a = 7
while n <=10:
  print(a*n)
  n +=1

7
14
21
28
35
42
49
56
63
70


In [ ]:
n = 0
while n < 5:
  print(n)
  n += 1

0
1
2
3
4


In [ ]:
#for loop.
for i in range(10):
  print(i, end = " ")

0 1 2 3 4 5 6 7 8 9 

In [ ]:
for i in range(11):
  if i == 4:
    print("skip this number.")
  else:
    print(i)

0
1
2
3
skip this number.
5
6
7
8
9
10


In [ ]:
#area calculator.
print("Press 1 to get the area of the circle.")
print("Press 2 to get the area of the rectangle.")
print("Press 3 to get the area of the square.")
num = int(input("Enter any number in between 1 and 3-"))
if num == 1:
  radius = float(input("Enter the radius of the circle-"))
  print("The area of the circle is-", 2*22/7*radius)
elif num == 2:
  length = float(input("Enter the length of the rectangle-"))
  width = float(input("Enter the width of the rectangle-"))
  print("The area of the rectangle is", length*width)
elif num == 3:
  side = float(input("Enter the side of the square: "))
  print("The area of the square is-", side*side)
else:
  print("INVALID INPUT!!")

Press 1 to get the area of the circle.
Press 2 to get the area of the rectangle.
Press 3 to get the area of the square.
Enter any number in between 1 and 3-2
Enter the length of the rectangle-3
Enter the width of the rectangle-4
The area of the rectangle is 12.0


In [ ]:
#write a program to check if a number is positive.
number = int(input("Enter any number here: "))
if number >= 1:
  print("It is a positive number.")
else:
  print("It is a negative number.")

Enter any number here: -9
It is a negative number.


In [ ]:
marks = 68
if marks > 80:
  print("A good score.")
elif marks > 70 and marks <79:
  print("Well done, but also need to improve.")
else:
  print("A good person but you have to work hard.")

A good person but you have to work hard.


In [ ]:
#short hand if statement.
marks = 89
print("you will go for a trip") if marks > 80 else print("You will go for study.")

you will go for a trip


In [ ]:
#membership operator.
a = "abciajfkj"
"a" in a

True

In [ ]:
#identity operator
a = 123
b = "123"
a is b

False

In [ ]:
#operators
n = 0
while n < 5:
  n += 1
  print(n)

1
2
3
4
5


In [ ]:
inp = int(input("Enter any integer here: "))
inp = float(inp)
print(inp)

Enter any integer here: 2
2.0


In [ ]:
#write a program to take the details for a identity card.
name = input("Enter the name of the student: ")
age = int(input("Enter the age of the student: "))
clas = input("Enter the class of the student: ")
roll_no = input("Enter the roll number of the student: ")

Enter the name of the student: Harita
Enter the age of the student: 23
Enter the class of the student: 4TH
Enter the roll number of the student: 21


In [ ]:
#convert float into string.
flot = 1.23
flot = int(flot)
print(flot)

1


In [ ]:
#write a program to swap two variables.
a = 12
b = 24
a,b = b,a
print(a)
print(b)

24
12


In [ ]:
#Palindrome
inp = input("Enter anything here to find palindrome: ")
if inp == inp[::-1]:
  print("It is a palindrmoe.")
else:
  print("Not a palindrome.")

Enter anything here to find palindrome: 323
It is a palindrmoe.


In [ ]:
#factorial
def fact(n):
  if n == 1:
    return n
  else:
    return n*fact(n-1)
fact(5)

120

In [ ]:
#fibonacci
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c
fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [ ]:
#palindrome
num = input('Enter anything here: ')
if num == num[: : -1]:
  print("It is a palindrome")
else:
  print("Not a palindrome.")

Enter anything here: 121
It is a palindrome


In [ ]:
#factorial
def fact(n):
  if n == 1:
    return n
  else:
    return n*fact(n-1)
fact(5)

120

In [ ]:
#zip function
names = ["Radhe", "Prem", "Tiger", "Avinash"]
marks = [57, 47, 85, 57]
results = zip(names, marks)
print(list(results))

[('Radhe', 57), ('Prem', 47), ('Tiger', 85), ('Avinash', 57)]


In [ ]:
#to show the palindrome
num = input('Enter anything here: ')
rev = 0
if num[::-1] == rev:
  print("It is a palindrome.")
else:
  print("It is not a palindrome.")

Enter anything here: 121
It is not a palindrome.


In [ ]:
add_num = [1,2,3,4,5,6]
def add(add_num):
  total = 0
  for i in add_num:
    total = total + i
  return total
add(add_num)

21

In [ ]:
def add(numbers):
  total = 0
  for i in numbers:
    total = total + i
    return (total)
add([1,2,3,4])



1

In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a, end = " ")
    c = a + b
    a = b
    b = c
fibonacci(10)





0 1 1 2 3 5 8 13 21 34 

In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c
fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [ ]:
def fact(n):
  if n == 1:
    return n
  else:
    return (n*fact(n-1))
fact(5)

120

In [ ]:
a = {1,2,3,4,5,6,7}
b = {4,5,6,7}
print(a.issubset(b))
print(b.issubset(a))

False
True


In [ ]:
#write a program to remove an element in a set.
a = {1,2,3,4,5}
a.discard(5)
print(a)

{1, 2, 3, 4}


In [ ]:
#write a program to find the difference between two sets.
a = {1,2,3,4,5}
b = {3,4,5,6,7}
a.difference(b)

{1, 2}

In [ ]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]
c = [1,2,4,2,5]
print(set(a)&set(b)&set(c))

{2, 4, 5}


In [ ]:
#write a function to find the maximum and the minimum number in a set.
a = {1, 2, 3, 4, 2, 4, 2}
max(a)
min(a)


1

In [ ]:
#fibonacci
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c
fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [ ]:
#write a function to get the maximum of three numbers.

def max_num(n1,n2,n3):
  if n1 > n2 and n1 > n3:
    print(n1,"is the maximum number.")
  elif n2 > n1 and n2 > n3:
    print(n2,"is the maximum number.")
  else:
    print(n3,"is the maximum number.")
max_num(5,2,3)

5 is the maximum number.


In [ ]:
#values and their squares.
def creat_list():
  l = []
  for i in range(1,11):
    l.append(i*i)
  return l
creat_list()

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
#lambda function.
x = lambda a,b,c : (a+b)*c
x(1,2,3)

9

In [ ]:
def fibonacci_series(n):
  a,b = 0,1
  for i in range(n):
    print(a, end = " ")
    c = a + b
    a = b
    b = c
fibonacci_series(10)

0 1 1 2 3 5 8 13 21 34 

In [ ]:
pdef fibo(num):
  if num == 1:
    return (0)
  elif num == 2:
    return (1)
  else:
    return (fibo(num-1) + fibo(num-2))
fibo(10)

34

In [ ]:
#write a function to sum all the numbers in a list.
numbers = [1,2,3,4]
def add(numbers):
  total = 0
  for i in numbers:
    total = total + i
  return total
add(numbers)

10

In [ ]:
def check_p(n):
  if n == 1:
    print("Not a prime number.")
  elif n == 2:
    print("A prime number.")
  else:
    for i in range(2,n):
      if n%i != 0:
        print("Prime Number")
        break
      else:
        print("Not a prime number.")
check_p(9)

Prime Number


In [ ]:
def check_prime(n):
  if n == 1:
    print("Not Prime")
  if n == 2:
    print("Prime")
  if n > 2:
    for i in range(2,n):
      n % i == 0
      print("It is not a prime number.")
      break
  else:
    print("It is a prime number.")
check_prime(11)

It is not a prime number.


In [ ]:
def fact(n):
  if n == 1:
    return n
  else:
    return n*fact(n-1)
fact(4)

24

In [ ]:
#To find the fibonacci series.
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a, end = " ")
    c = a + b
    a = b
    b = c
fibonacci(10)

0 1 1 2 3 5 8 13 21 34 

In [ ]:
sum = 0
def fact(n):
  if n == 0 or n == 1:
    return n
  else:
    sum = n*fact(n-1)
    return sum

fact(5)


120

In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c
fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [ ]:
#to find the prime number.

In [ ]:
#a = "Hello World"
#a.istitle()

#to find the number of vowel in a string.
v = input("enter anything here: ")
vow = 0
for i in vow:
  if i == "a" or i == "A" or i == "e" or i == "E" or i == "I" or i == "i" or i == "O" or i == "o" or i == "u" or i == "U":
    vow+=1

enter anything here: U


TypeError: 'int' object is not iterable

In [ ]:
def marks(num):
  if num>80:
    print("You will get a mobile")
  else:
    print("You really need an improvement.")

marks(89)


In [ ]:
def mark(marks):
  if marks > 80:
    print("You are appreciated.")
  else:
    print("Needs improvement")
mark(78)

Needs improvement


In [ ]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(1,11):
  if i == 5:
    print("You are dismissed")
  else:
    print(i)

1
2
3
4
You are dismissed
6
7
8
9
10


In [ ]:
def add(x,y):
  print(x+y)

add(3,4)

7


In [ ]:
a = ["Rohit", "Sohan", "Mohan", "Priya", "Greena"]

print(a)

['Rohit', 'Sohan', 'Mohan', 'Priya', 'Greena']


In [ ]:
print(a[1])

Sohan


In [ ]:
print(a[::-1])
print()
print(a[:2])
print(a[-3:-1])

['Greena', 'Priya', 'Mohan', 'Sohan', 'Rohit']

['Rohit', 'Sohan']
['Mohan', 'Priya']


In [ ]:
print(a[1:3])

['Sohan', 'Mohan']


In [ ]:
for i in range(1,101):
  if i%8==0 and i%12==0:
    print(i)

24
48
72
96


In [ ]:
#2*3.14*r
def area(r):
  print(2*3.14*r)

area(7)


43.96


In [ ]:
def rect_area(length,breath):
  print(length*breath)

rect_area(4,3)

12


In [ ]:
a = 1,2,3
b = "1,2,3"
a is b

False

In [ ]:
def mul(n):
  print(7*n)

mul(7)

49


In [ ]:
n = 7
for i in range(1,11):
  print(7*i)

7
14
21
28
35
42
49
56
63
70


In [ ]:
marks = 98
print("You are a good student") if marks>90 else print("You are an average student")

You are a good student


In [ ]:
a = 7
b = 1
while b<=10:
  print(a*b)
  b+=1

7
14
21
28
35
42
49
56
63
70


In [ ]:
#Numpy stands for numeric python.
#deals with array.
#a library of python.
#numpy stores less memory.
#directly apply the math functions.
#performing faster.

import numpy as np

a = np.array([1,2,3,4])
print(a)

print(type(a))

print()

#Math operation in list
a = [1,2,3,4,5]
b = [1,2,3,4,5]
print(a+b)

print()


a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

print(a+b)

[1 2 3 4]
<class 'numpy.ndarray'>

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

[ 2  4  6  8 10]


In [ ]:
arr = np.array([10, 23, 24, 25, 53, 53, 53])
print(arr)


print(arr[1])

[10 23 24 25 53 53 53]
23


In [ ]:
#One-Dimensional Array.

a = np.array([3,4,5,2,3,6])
print(a)


#Slicing in one dimensional array.
a = np.array([3,4,5,2,3,6])
a[::-1]

[3 4 5 2 3 6]


array([6, 3, 2, 5, 4, 3])

In [ ]:
#2-dimensional array.

a = np.array([[1,2],
             [3,4]])
print(a)

#slicing in 2-dimensional array.
a = np.array([[1,2],
             [3,4]])

print(a[1])

print()

print(a[0])

print()

print(a[0:1])

print()

print(a[0:2])

print()

print(a[1][1])

[[1 2]
 [3 4]]
[3 4]

[1 2]

[[1 2]]

[[1 2]
 [3 4]]

4


In [ ]:
#3-dimensional array.

a = np.array([[[12,13,14],
               [12,13,14],
               [12,13,14]]])
print(a)

[[[12 13 14]
  [12 13 14]
  [12 13 14]]]


In [ ]:
#Slicing in the 3-dimensional numpy array.
import numpy as np
a = np.array([[[12,13,14],
               [12,13,14],
               [12,13,14]]])
print(np.ndim(a))

3


In [ ]:
a = np.array([[1,2],
             [3,4]])
print(np.ndim(a))

2


In [ ]:
import numpy as np
a = np.array([[[12,3,4],
               [12,1,1],
               [12,3,1]]])

print(a[0][1])
print()
print(a[0][2])
print()
print(a[0][1])
print()
print(a[0][1][1])
print()
print(a[0][2][1])

[12  1  1]

[12  3  1]

[12  1  1]

1

3


In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

print(type(a))
print()
print(a.astype(int))
print()
print(len(a))
print()
print(a.shape)
print()
print(a.size)
print()
print(a.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>

[1 2 3 4 5]

5

(5,)

5

1


In [ ]:
a = np.array([[1,2],[3,4]])
print(type(a))
print(a.ndim)
print(a.size)
print(a.dtype)
print(len(a))

<class 'numpy.ndarray'>
2
4
int64
2


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(arr1+arr2)

[[ 6  8]
 [10 12]]


In [ ]:
b = np.concatenate([arr1,arr2])
print(len(b))
print(b)


4
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(b[3][1])

8


In [ ]:
#spliting in array
arry = np.array([1,2,3,4,5,6])
print(np.array_split(arry,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
c = np.array([1,2,3,4,5,6,7,8,9])
d = np.array_split(c,5)

In [ ]:
print(d[1])

[3 4]


In [ ]:
a = np.array([1,2,3,4,5])
np.append(a,6)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.insert(a,1,8)

array([1, 8, 2, 3, 4, 5])

In [ ]:
np.delete(a,[1])

array([1, 3, 4, 5])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.ndim

1

In [ ]:
len(arr)

8

In [ ]:
arr.size

8

In [ ]:
arr.shape

(8,)

In [ ]:
a = np.array([[1,2],[3,4]])
a.shape

(2, 2)

In [ ]:
arr = np.array([1,2,3,4,5,6])
np.append(arr,2)

array([1, 2, 3, 4, 5, 6, 2])

In [ ]:
np.insert(arr,1,9)

array([1, 9, 2, 3, 4, 5, 6])

In [ ]:
np.delete(arr,[1])

array([1, 3, 4, 5, 6])

In [ ]:
print(arr.size)
print(arr.dtype)
print(arr.ndim)
print(arr.astype(int))
print(len(arr))

6
int64
1
[1 2 3 4 5 6]
6


In [ ]:
hel = np.array([23,4,53,2,5,3,6,72])
print(np.sort(hel))

[ 2  3  4  5  6 23 53 72]


In [ ]:
a = np.array([1,2,3,4])
np.where(a==2)

(array([1]),)

In [ ]:
np.where(arr==4)

(array([3]),)

In [ ]:
#filtering the array manually
arry = np.array([1,2,3,4])
fa = [True,False,True,False]
new = arry[fa]
print(new)

[1 3]


In [ ]:
elem = np.array([1,2,3,4,5,6])
s = np.where(elem%2==0)
print(s)

(array([1, 3, 5]),)


In [ ]:
#Creating a dictionary.
#Dictionary allows the user to write the data in the form of key and its values.
#The keys and values are separated by semicolon.
#We are using a curly brackets to create a dictionary.

employee = {"Name": "John", "Age": 34, "Gender": "Male"}
print(employee)

{'Name': 'John', 'Age': 34, 'Gender': 'Male'}


In [ ]:
print(employee["Name"])
print(employee["Age"])
print(employee["Gender"])

John
34
Male


In [ ]:
import pandas as pd

In [ ]:
employee = {"Name": ["John"], "Age": [34], "Gender": ["Male"]}
df = pd.DataFrame(employee)
df

Name  Age Gender
0  John   34   Male

In [ ]:
employee = {"name": ["john", "robin", "kailash"],
            "age": [23, 45, 56],
            "Gender": ["Male", "Male", "Male"]}
df = pd.DataFrame(employee)
df

name  age Gender
0     john   23   Male
1    robin   45   Male
2  kailash   56   Male

In [ ]:
for i in employee:
  print(i)

name
age
Gender


In [ ]:
for i in employee:
  print(employee[i])

['john', 'robin', 'kailash']
[23, 45, 56]
['Male', 'Male', 'Male']


In [ ]:
print(employee.items())

dict_items([('name', ['john', 'robin', 'kailash']), ('age', [23, 45, 56]), ('Gender', ['Male', 'Male', 'Male'])])


In [ ]:
print(employee["name"])

['john', 'robin', 'kailash']


In [ ]:
for x,y in employee.items():
  print(x,y)

name ['john', 'robin', 'kailash']
age [23, 45, 56]
Gender ['Male', 'Male', 'Male']


In [ ]:
for x in employee.values():
  print(x)

['john', 'robin', 'kailash']
[23, 45, 56]
['Male', 'Male', 'Male']


In [ ]:
for x in employee.keys():
  print(x)

name
age
Gender


In [ ]:
for i in range(1,202):
  if i%8==0 and i%12==0:
    print(i)

24
48
72
96
120
144
168
192


In [ ]:
def add(x,y):
  print(x+y)

add(2,3)

5


In [ ]:
def area_square(side):
  print(side*side)

area_square(4)

16


In [ ]:
for i in range(1,3):
  for j in range(1,5):
    print(j)

1
2
3
4
1
2
3
4


In [ ]:
#Sets = sets are the collections of unique datas.


In [ ]:
num1 = int(input("Enter a number here: "))
num2 = int(input("Enter another number here: "))
print(num1+num2)

Enter a number here: 8
Enter another number here: 8
16


In [ ]:
def add():
  num1 = int(input('Enter a number here: '))
  num2 = int(input('Enter another number here: '))
  print(num1+num2)

add()

Enter a number here: 7
Enter another number here: 7
14


In [ ]:
a = 1.23
b = int(a)
b

1

In [ ]:
type(b)

int

In [ ]:
name = input("Enter your name here: ")
age = int(input("Enter your age here: "))
roll_no = int(input("Enter your roll number here: "))
gender = input("Enter your gender here: ")

Enter your name here: Jasleen
Enter your age here: 23
Enter your roll number here: 21
Enter your gender here: Male


In [ ]:
#creating a nested dictionary.
dict = {1: {"Name": "John", "Age": 23, "Gender": "Male"},
        2: {"Name": "Preeti", "Age": 32, "Gender": "Female"}}
print(dict)

{1: {'Name': 'John', 'Age': 23, 'Gender': 'Male'}, 2: {'Name': 'Preeti', 'Age': 32, 'Gender': 'Female'}}


In [ ]:
print(dict[1])

{'Name': 'John', 'Age': 23, 'Gender': 'Male'}


In [ ]:
print(dict[1]["Name"])

John


In [ ]:
dict = {"Name": "John", "Age": 23, "Gender": "Male"}
print(dict)

{'Name': 'John', 'Age': 23, 'Gender': 'Male'}


In [ ]:
dict.keys()

dict_keys(['Name', 'Age', 'Gender'])

In [ ]:
dict.values()

dict_values(['John', 23, 'Male'])

In [ ]:
dict.get("Name")

'John'

In [ ]:
dict.items()

dict_items([('Name', 'John'), ('Age', 23), ('Gender', 'Male')])

In [ ]:
dict.setdefault("Age",24)

23

In [ ]:
print(dict["Age"])

23


In [ ]:
#Iteration in dictionary.
a = {1,2,3,4,5}
for i in a:
  print(i, end = " ")

1 2 3 4 5 

In [ ]:
dict = {"Name": "John", "Age": 23, "Gender": "Male"}

for x in dict.values():
  print(x)

John
23
Male


In [ ]:
for x in dict.keys():
  print(x)

Name
Age
Gender


In [ ]:
for x,y in dict.items():
  print(x,y)

Name John
Age 23
Gender Male


In [ ]:
#Sets
a = {"Ironman", "Thor", "Bahubali", "Superman"}


In [ ]:
a.pop()
print(a)

{'Bahubali', 'Superman', 'Thor'}


In [ ]:
a

{'Bahubali', 'Superman', 'Thor'}

In [ ]:
a.add("Batman")

In [ ]:
a

{'Bahubali', 'Batman', 'Superman', 'Thor'}

In [ ]:
a.remove("Superman")
print(a)

{'Bahubali', 'Thor', 'Batman'}


In [ ]:
a.discard("Thor")
a

{'Bahubali', 'Batman'}

In [ ]:
b = a.copy()
print(b)

{'Bahubali', 'Batman'}


In [ ]:
list1 = [1,2,3,4,5]
list1.append(6)
print(list1)

[1, 2, 3, 4, 5, 6]


In [ ]:
list1.remove(6)
print(list1)

[1, 2, 3, 4, 5]


In [ ]:
list1.pop()

5

In [ ]:
list1

[1, 2, 3, 4]

In [ ]:
list1.append(5)
print(list1)

[1, 2, 3, 4, 5, 5]


In [ ]:
list1.count(2)  #to count the occurence of the element in the list.

1

In [ ]:
list1.insert(1,7)
print(list1)

[1, 7, 7, 7, 7, 2, 3, 4, 5, 5]


In [ ]:
list1.pop(2)

7

In [ ]:
avengers = ["Spiderman", "Batman", "Krish"]
avengers[0]

'Spiderman'

In [ ]:
avengers.append("Hulk")
print(avengers)

['Spiderman', 'Batman', 'Krish', 'Hulk', 'Hulk']


In [ ]:
avengers.remove("Hulk")

In [ ]:
print(avengers)

['Spiderman', 'Batman', 'Krish', 'Hulk']


In [ ]:
#write a program to find a sum of all even numbers upto 50.
sum = 0
for i in range(1,51):
  if num % 2== 0:
    sum+=i
print("The sum of the even numbers upto 50 is ", sum)

The sum of the even numbers upto 50 is  1275


In [ ]:
a = ["Jammu", "New Delhi", "Mumbai"]
b = ["Madhya Pradesh", "Shimla"]
print(a+b)

['Jammu', 'New Delhi', 'Mumbai', 'Madhya Pradesh', 'Shimla']


In [ ]:
a = ["Jammu", "New Delhi", "Mumbai"]
b = ["Madhya Pradesh", "Shimla"]
print(a[1])
print()
print(a.index("Jammu"))

New Delhi

0
None


In [ ]:
a = ["Jammu", "New Delhi", "Mumbai"]
b = ["Madhya Pradesh", "Shimla"]
a.extend(b)
print(a)

['Jammu', 'New Delhi', 'Mumbai', 'Madhya Pradesh', 'Shimla']


In [ ]:
a.index("New Delhi")

1

In [ ]:
num = []
for num in range(1,51):
  if i%2==0:
    num=i
print(num)

100


In [ ]:
sum = 0
for i in range(1,51):
  if num % 2== 0:
    sum+=i
print(sum)

1275


In [ ]:
name = "Jasmine"
age = 23
address = "L-83 Border Street New Delhi-110033"
print(name)
print(age)
print(address)

Jasmine
23
L-83 Border Street New Delhi-110033


In [ ]:
a = "Rohit, Raj"
b = "Rani, Shalini"
a,b = b,a

In [ ]:
print(a)

Rani, Shalini


In [ ]:
a = 1.23
b = int(a)
print(b)

1


In [ ]:
name = input("Enter a name here: ")
age = int(input("Enter your age here: "))
gender = input("Enter your gender here: ")

Enter a name here: Hira Lal
Enter your age here: 43
Enter your gender here: Male


In [ ]:
user_input = int(input("Enter number here: "))
user_input = float(user_input)
print(user_input)

Enter number here: 3
3.0


In [ ]:
#Logical operators- AND, OR, NOT
3>2 and 2<4

True

In [ ]:
3>1 or 3<4

True

In [ ]:
not(3>1 or 3<1)

False

In [ ]:
not(1>2 and 0>1)

True

In [ ]:
a = 123
b = "123"
print(a is b)
print(a is not b)

False
True


In [ ]:
a = "aeiou"
"i" in a
"ei" in a

True

In [ ]:
amount = 45
if amount >50:
  print("He is a rich person")
elif amount > 40:
  print("He is going to be rice")
else:
  print("He is a happy person.")

He is going to be rice


In [ ]:
for i in range(1,5):
  if i == 2:
    continue
  else:
    print(i)

1
3
4


In [ ]:
for i in range(1,11):
  if i == 5:
    break
  else:
    print(i)

1
2
3
4


In [ ]:
x = lambda a,b,c: (a+b)*c
x(1,2,3)

9

In [ ]:
[i for i in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
count = 1
while count<=5:
  print(count)
  count+=1

1
2
3
4
5


In [ ]:

student = {"name": "Rashi", "age": 34, "roll no": 23, "gender": "female"}
for x in student:
  print(x)

name
age
roll no
gender


In [ ]:
student = {"name": "Rashi", "age": 34, "roll no": 23, "gender": "female"}
for x in student.items():
  print(x)

('name', 'Rashi')
('age', 34)
('roll no', 23)
('gender', 'female')


In [ ]:
student = {"name": "Rashi", "age": 34, "roll no": 23, "gender": "female"}
for x in student.values():
  print(x)


Rashi
34
23
female


In [ ]:
student = {"name": "Rashi", "age": 34, "roll no": 23, "gender": "female"}
for i in student.keys():
  print(i)

name
age
roll no
gender


In [ ]:
                                    ##Python from the start.
print("hello world")

hello world


In [ ]:
#data types in python- Text datatypes, integer dtypes, sequence dtypes, map dtypes,
#String, int, float, boolean, list, tuple, dictionary.

In [ ]:
#Taking the inputs from the user.
name = input("Enter a name here: ")
age = int(input("Enter the age here: "))
gender = input("Enter the gender here: ")

Enter a name here: Lara
Enter the age here: 23
Enter the gender here: Female


In [ ]:
#String- Whatever is comes under the inverted comma called string. It can be anything like int, float, boolean, text anything.

In [ ]:
#Typecasting- 2 Types of typecasting occurs
#1. Implicit- During the time of conversion or while performing the task python can change the dtypes by itself.
#2. Explicit- User has to change the dtypes from one type to another.

#Implicit
a = 123
b = 1.23
print(a+b)


#Explicit
a = 1.23
b = "123"
b = float(b)
print(a+b)

124.23
124.23


In [ ]:
                                                    #QUESTIONS
#Write a program to swap two variable.
a = "1,2,3"
b = "3,4,5"
a,b = b,a
print(a)
print(b)

#converting float into integer.
a = 1.23
b = int(a)
print(b)

3,4,5
1,2,3
1


In [ ]:
#Write the program to fill the id card for a student.
def student_details():
  input("Enter the name of the person: ")
  input("Enter the age of the person: ")
  input("Enter the roll number of the person: ")

student_details()

Enter the name of the person: Alisha
Enter the age of the person: 23
Enter the roll number of the person: 21


In [ ]:
#Take the user input as an integer and convert it into float.
                                          #Check because this function is running but not correctly
#def convert():
#  user_input = int(input("Enter the float number here: "))
#  user_input = float(user_input)

#convert()

user_input = int(input("Enter a number here: "))

converted_input = float(user_input)


print(converted_input)

Enter a number here: 3
3.0


In [ ]:
#Here we have total 6 types of operators-
#Arithmatic Operator - addition(+), substraction(-) etc
#Comparision Operator - "==", "<=" ">=" etc
#Identity Operator - "is" or "is not"
#Membership Operator- "in" or "not in"
#Logical Operator- AND, OR, NOT
#Assignment Operator-

In [ ]:
sugar = 350
if sugar>400:
  print("You will be in danger soon.")
elif sugar> 300 and sugar<=400:
  print("You should immidiatly take the prevention")
else:
  print("Do excercise daily.")

You should immidiatly take the prevention


In [ ]:
marks = 68
print("You will go for picnic") if marks>70 else print("Go and read again then come for exams")

Go and read again then come for exams


In [ ]:
x = lambda a,b,c: (a+b)*c
x(3,3,5)

30

In [ ]:
#Taking a variable as an integer and converting it into float.
user_input = int(input("Enter a number here: "))

converted_input = float(user_input)


print(converted_input)

Enter a number here: 2
2.0


In [ ]:
a = "1,3,4"
b = [2,3,4]
print(a is b)

print(a is not b)

False
True


In [ ]:
marks = 97
print("You will definitely win the prize") if marks > 89 else print("good luck")

You will definitely win the prize


In [ ]:
sum = 0
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [ ]:
#List Comprehension
#Square of a number till 10 by using list comprehension.

square = [x**2 for x in range(1,11)]
print(square)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
even_number = [x for x in range(1,51) if x%2==0]
print(even_number)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


In [ ]:
pos_num = int(input("Enter a number here: "))
def pos_num():
  if pos_num >=0:
    print("It is a positive number")
  else:
    print("It is a negative number")

Enter a number here: 4


In [ ]:
#writing a program to check whether a number is positive or negative.
num = int(input("Enter a number here: "))
if num >= 0:
  print("It is a positive number")
else:
  print("It is a negative number")

Enter a number here: 3
It is a positive number


In [ ]:
#write a program to check a number is odd or even.
num = int(input("Enter any number here: "))
if num % 2 == 0:
  print("It is a even number ")
else:
  print("It is a odd number")

Enter any number here: 3
It is a odd number


In [ ]:
#write a program to check area calculator.

##                area calculator
#press 1 to find the area of a square.
#press 2 to find the area of the rectangle.

num = int(input("Enter a number here: "))
if num == 1:
  side = float(input("Enter the side of the square: "))
  area_sq = side*side
  print(area_sq)
elif num == 2:
  length = float(input("Enter the length of the rectangle: "))
  breath = float(input("Enter the breath of the rectangle: "))
  area_rect = length*breath
  print(area_rect)
else:
  print("Invalid Input")

Enter a number here: 2
Enter the length of the rectangle: 6
Enter the breath of the rectangle: 6
36.0


In [ ]:
#write a program to check whether the pass letter is a vowel of consoment.
letter = "d"
if letter in "aeiou" or letter in "AEIOU":            #we are using membership operator here.
  print("It is a vowel")
else:
  print("It is a consonent")

It is a consonent


In [ ]:
#write a program to check if a number is a single digit number or double digit number.
number = int(input("Enter a number here: "))
if number >= 0 and number <= 9:
  print("It is a single digit number.")
elif number >= 10 and number <= 99:
  print("It is a double digit number.")
else:
  print("INVALID INPUT")

Enter a number here: 88
It is a double digit number.


In [ ]:
#For Loop.
for i in range(1,11):
  print(f"The square of the {i} is", i*i)

The square of the 1 is 1
The square of the 2 is 4
The square of the 3 is 9
The square of the 4 is 16
The square of the 5 is 25
The square of the 6 is 36
The square of the 7 is 49
The square of the 8 is 64
The square of the 9 is 81
The square of the 10 is 100


In [ ]:
import pandas as pd

In [ ]:
#Some of the concepts of pandas.
data = {"Name": ["Naman", "Jasmine", "Kritisha"],
        "Age": [23, 43, 35],
        "Gender": ["Female", "Female", "Female"]}
df = pd.DataFrame(data)
df

Name  Age  Gender
0     Naman   23  Female
1   Jasmine   43  Female
2  Kritisha   35  Female

In [ ]:
from google.colab import drive
drive.mount("/content/drive/")

Mounted at /content/drive/


In [ ]:
path = "/content/sample_data/california_housing_test.csv"
data = pd.read_csv(path)
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [ ]:
data.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0

In [ ]:
data["housing_median_age"].mean()

28.845333333333333

In [ ]:
data.duplicated().sum()

0

In [ ]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


In [ ]:
print(data["total_rooms"].duplicated().sum())

785


In [ ]:
print(data.drop_duplicates("total_rooms"))

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2987    -121.97     37.29                25.0       4096.0           743.0   
2989    -122.02     37.60                32.0       1295.0           295.0   
2991    -117.17     34.28                13.0       4867.0           718.0   
2992    -122.33     37.39                52.0        573.0           102.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   

      population  households  median_income  median_house_value

In [ ]:
data.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
employee = {"Name": ["Bishwas", "Roy", "Tom", "Lisa", "Lovely", "Rashmi"],
            "Age": [23, 34, 33, 23, 29, 32],
            "Gender": ["Female", "Male", "Male", "Female", "Female", None]}

In [ ]:
df = pd.DataFrame(employee)
df

Name  Age  Gender
0  Bishwas   23  Female
1      Roy   34    Male
2      Tom   33    Male
3     Lisa   23  Female
4   Lovely   29  Female
5   Rashmi   32    None

In [ ]:
df.duplicated("Age")

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

In [ ]:
df.drop_duplicates("Age")

Name  Age  Gender
0  Bishwas   23  Female
1      Roy   34    Male
2      Tom   33    Male
4   Lovely   29  Female
5   Rashmi   32    None

In [ ]:
df.fillna("Female")

Name  Age  Gender
0  Bishwas   23  Female
1      Roy   34    Male
2      Tom   33    Male
3     Lisa   23  Female
4   Lovely   29  Female
5   Rashmi   32  Female

In [ ]:
df["Gender"].fillna("Female", inplace=True)

In [ ]:
df

Name  Age  Gender
0  Bishwas   23  Female
1      Roy   34    Male
2      Tom   33    Male
3     Lisa   23  Female
4   Lovely   29  Female
5   Rashmi   32  Female

In [ ]:
df.loc[df["Gender"] == "Female"]

Name  Age  Gender
0  Bishwas   23  Female
3     Lisa   23  Female
4   Lovely   29  Female
5   Rashmi   32  Female

In [ ]:
#write a program to swap two variables.
a = 12
b = 13
temp = 12
a = b
b = temp
print(a)
print()
print(b)

13

12


In [ ]:
num = int(input("Enter a integer here: "))
num = float(num)
print(num)
print(type(num))

Enter a integer here: 4
4.0
<class 'float'>


In [ ]:
#logical operator
2>4 and 3>1

False

In [ ]:
a = 123
b = 1.23
print(a is b)
print(a is not b)

False
True


In [ ]:
a = "aeiou"
print("a" not in a)
print("a" in a)

False
True


In [ ]:
#if statement
marks = 84
if marks > 80:
  print("You will win the award.")

You will win the award.


In [ ]:
#short hand if statement.
marks = 80
if marks > 70: print("Very well")

Very well


In [ ]:
#short hand if-else statement.
marks = 67
print("You are a good student") if marks > 85 else print("You really need to imporve yourself.")

You really need to imporve yourself.


In [ ]:
#write a program to check a number is positive.
num = int(input("Enter a number here "))
if num > 0:
  print("It is a positive number.")
else:
  print("It is a negative number")

Enter a number here 9
It is a positive number.


In [ ]:
number = int(input("Enter a number here: "))
if number % 2 == 0:
  print ("We got an even number here as an input.")
else:
  print("Sadly, we got an odd number.")

Enter a number here: 7
Sadly, we got an odd number.


In [ ]:
#write a program to check whether the number is a vowel or not.
letter = input("Enter any letter here: ")
if letter in "aeiou" and letter in "AEIOU":
  print("It is a vowel")
else:
  print("It is a consonent or not vowel.")

Enter any letter here: K
It is a consonent or not vowel.


In [ ]:
#To check the number of digits.
num = int(input("Enter number here: "))
if num >= 0 and num < 9:
  print("Single digit number.")
elif num >= 10 and num <= 99:
  print("Double digits!!")
elif num >=100 and num <= 999:
  print("Three digits number.")
else:
  print("Invalid Input!!")

Enter number here: 888
Three digits number.


In [ ]:
#for loop
for i in range(1,6):
  print(i)

1
2
3
4
5


In [ ]:
for i in range(1,6):
  if i == 3:
    continue
  else:
    print(i)

1
2
4
5


In [ ]:
for i in range(1,11):
  if i == 5:
    break

In [ ]:
for i in range(1,23):
  if i == 5:
    break
  else:
    print(i)

1
2
3
4


In [ ]:
#while loop
n = 1
while n <= 5:
  print(n)
  n+=1

1
2
3
4
5


In [ ]:
#table of 5 using while loop.
n = 1
a = 5
while n<=10:
  print(a, "x", n,"=",a*n)
  n+=1

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [ ]:
n = 7
for i in range(1,11):
  print(n*i)


7
14
21
28
35
42
49
56
63
70


In [ ]:
def count_upto(n):
  count = 1
  while count <= 10:
    yield count
    count += 1

counter = count_upto(10)

for i in counter:
  print(i)



1
2
3
4
5
6
7
8
9
10


In [ ]:
#What are generators?
#Generators are the special type of iterables that generates the value without storing the memory.
#one of the major advantages of this generators is it is memory efficient.

def count_up_to(n):
  count = 1
  while count<=5:
    yield count
    count+=1

counter = count_up_to(5)

for number in counter:
  print(number)

In [ ]:
#again
def count_up_to(n):
  count = 1
  while count<=10:
    yield count
    count+=1
counter = count_up_to(10)

for i in counter:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
#What is exceptional handling in python.
#exceptional handling in python is used to prevent crashes or to avoid erros.
#We use try, except and finally to handle the exception.

try:
  num = int(input("Enter a number here: "))
  print(10/num)
except ZeroDivisionError:
  print("Cannot divided by zero!")
except ValueError:
  print("Invalid Input!")
else:
  print("Division Successful!")
finally:
  print("Program Completed")

Enter a number here: -
Invalid Input!
Program Completed


In [ ]:
#What is decorator?
#A decorator is used to modify or extend the behaviour of the function without changing it's original structure.
#Advantages- Enhance functionality, Reusable.

In [ ]:
#lambda function.
x = lambda a,b,c: (a+b)*c
print(x(1,2,3))

9


In [ ]:
def count_upto(n):
  count = 1
  while count<=5:
    yield count
    count+=1

counter = count_upto(5)

for i in counter:
  print(i)

1
2
3
4
5


In [ ]:
#
def count_upto(n):
  count = 1
  while count <= 5:
    yield count
    count += 1

counter = count_upto(5)

for i in counter:
  print(i)

1
2
3
4
5


In [ ]:
#lambda function.
x = lambda a,b,c: (a+b)*c
print(x(1,2,3))

9


In [ ]:
import pandas as pd

In [ ]:
df = {"Name": ["Hari", "Priya", "Rathiram", "July"],
      "Age": [24, 35, 23, 25],
      "Gender": ["Male", "Female", "Male", "Female"]}
df = pd.DataFrame(df)
df

Name  Age  Gender
0      Hari   24    Male
1     Priya   35  Female
2  Rathiram   23    Male
3      July   25  Female

In [ ]:
age = df.loc[df["Age"]>24]             #loc method used to access the details of the data over a certain condition.

#age

print(df)

       Name  Age  Gender
0      Hari   24    Male
1     Priya   35  Female
2  Rathiram   23    Male
3      July   25  Female


In [ ]:
df.loc[df["Gender"] == "Male"]

Name  Age Gender
0      Hari   24   Male
2  Rathiram   23   Male

In [ ]:
df.loc[df["Gender"] == "Female"]

Name  Age  Gender
1  Priya   35  Female
3   July   25  Female

In [ ]:
print(df.iloc[0:3])  #iloc stands for index location.

       Name  Age  Gender
0      Hari   24    Male
1     Priya   35  Female
2  Rathiram   23    Male


In [ ]:
#Column transformation.
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"]}

df = pd.DataFrame(data)
df

First Name Last Name  Age  Gender
0     Rohini   Kashyap   23  Female
1        Raj     Kumar   45    Male
2       Rani       Raj   35  Female
3      Aasma     Sinha   29  Female

In [ ]:
df["FullName"] = df["First Name"] + " " + df["Last Name"]
df

First Name Last Name  Age  Gender        FullName
0     Rohini   Kashyap   23  Female  Rohini Kashyap
1        Raj     Kumar   45    Male       Raj Kumar
2       Rani       Raj   35  Female        Rani Raj
3      Aasma     Sinha   29  Female     Aasma Sinha

In [ ]:
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"],
        "Salary": [45000, 49000, 56000, 34000]}

df = pd.DataFrame(data)
df

First Name Last Name  Age  Gender  Salary
0     Rohini   Kashyap   23  Female   45000
1        Raj     Kumar   45    Male   49000
2       Rani       Raj   35  Female   56000
3      Aasma     Sinha   29  Female   34000

In [ ]:
df.loc[(df["Salary"] <35000), "GetsBonus"] = "Bonus"

df.loc[(df["Salary"]> 35000), "GetsBonus"] = "No Bonus"

df

First Name Last Name  Age  Gender  Salary GetsBonus
0     Rohini   Kashyap   23  Female   45000  No Bonus
1        Raj     Kumar   45    Male   49000  No Bonus
2       Rani       Raj   35  Female   56000  No Bonus
3      Aasma     Sinha   29  Female   34000     Bonus

In [ ]:
#GroupBy in Pandas.
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"],
        "Salary": [45000, 49000, 56000, 34000],
        "City": ["New Delhi", "Mumbai", "Hydrabad", "New Delhi"]}

df = pd.DataFrame(data)
df

First Name Last Name  Age  Gender  Salary       City
0     Rohini   Kashyap   23  Female   45000  New Delhi
1        Raj     Kumar   45    Male   49000     Mumbai
2       Rani       Raj   35  Female   56000   Hydrabad
3      Aasma     Sinha   29  Female   34000  New Delhi

In [ ]:
gp = df.groupby("City").size()
print(gp)


City
Hydrabad     1
Mumbai       1
New Delhi    2
dtype: int64


In [ ]:
import pandas as pd

In [ ]:
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"]}

df = pd.DataFrame(data)
df

First Name Last Name  Age  Gender
0     Rohini   Kashyap   23  Female
1        Raj     Kumar   45    Male
2       Rani       Raj   35  Female
3      Aasma     Sinha   29  Female

In [ ]:
df["Full Name"] = df["First Name"] + " " + df["Last Name"]

In [ ]:
df


First Name Last Name  Age  Gender       Full Name
0     Rohini   Kashyap   23  Female  Rohini Kashyap
1        Raj     Kumar   45    Male       Raj Kumar
2       Rani       Raj   35  Female        Rani Raj
3      Aasma     Sinha   29  Female     Aasma Sinha

In [ ]:
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"],
        "Salary": [45000, 49000, 56000, 34000]}

df = pd.DataFrame(data)
df

First Name Last Name  Age  Gender  Salary
0     Rohini   Kashyap   23  Female   45000
1        Raj     Kumar   45    Male   49000
2       Rani       Raj   35  Female   56000
3      Aasma     Sinha   29  Female   34000

In [ ]:
df.loc[(df["Salary"]> 35000), "Gets Bonus"] = "Bonus"
df.loc[(df["Salary"]< 34500), "Gets Bonus"] = "No Bonus"

In [ ]:
df

First Name Last Name  Age  Gender  Salary Gets Bonus
0     Rohini   Kashyap   23  Female   45000      Bonus
1        Raj     Kumar   45    Male   49000      Bonus
2       Rani       Raj   35  Female   56000      Bonus
3      Aasma     Sinha   29  Female   34000   No Bonus

In [ ]:
#GroupBy in Pandas.
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"],
        "Salary": [45000, 49000, 56000, 34000],
        "City": ["New Delhi", "Mumbai", "Hydrabad", "New Delhi"]}

df = pd.DataFrame(data)
df

First Name Last Name  Age  Gender  Salary       City
0     Rohini   Kashyap   23  Female   45000  New Delhi
1        Raj     Kumar   45    Male   49000     Mumbai
2       Rani       Raj   35  Female   56000   Hydrabad
3      Aasma     Sinha   29  Female   34000  New Delhi

In [ ]:
gp = df.groupby("City").size()
gp

City
Hydrabad     1
Mumbai       1
New Delhi    2
dtype: int64

In [ ]:
data = [
    {"category": "fruit", "item": "apple", "price": 1.2},
    {"category": "fruit", "item": "banana", "price": 0.5},
    {"category": "vegetable", "item": "carrot", "price": 0.7},
    {"category": "vegetable", "ite,m": "broccoli", "price": 1.0},
    {"category": "fruit", "item": "orange", "price": 1.3}
]

df = pd.DataFrame(data)
df

category      item  price
0      fruit     apple    1.2
1      fruit    banana    0.5
2  vegetable    carrot    0.7
3  vegetable  broccoli    1.0
4      fruit    orange    1.3

In [ ]:
df.groupby("category").sum()

item  price
category                           
fruit      applebananaorange    3.0
vegetable     carrotbroccoli    1.7

In [ ]:
name = ["Rohini", "Raj", "Rani", "Aasma"]
index = name.index("Rohini")
name[index] = "Ritika"
print(name)

['Ritika', 'Raj', 'Rani', 'Aasma']


In [ ]:
name = ["Rohini", "Raj", "Rani", "Aasma"]

# Find the index of "Raj" and replace it with "Rohini"
index = name.index("Raj")  # This finds the index of "Raj"
name[index] = "Rohini"     # Replace the element at that index

print(name)

In [ ]:
names = "Rani, Priya, Preeti, Priyanshi"
names.replace("Rani","Ishita")
print(names)

Rani, Priya, Preeti, Priyanshi


In [ ]:
name = ["Rohini", "Raj", "Rani", "Aasma"]
name.pop()
print(name)

['Rohini', 'Raj', 'Rani']


In [ ]:
for i in range(1,11):
  if i == 5:
    continue
  else:
    print(i)

1
2
3
4
6
7
8
9
10


In [ ]:
#not working
for i in range(1,11):
  if i == 5:
    continue
print(i)

10


In [ ]:
for i in range(1,11):
  if i == 5:
    break
  else:
    print(i)

1
2
3
4


In [ ]:
                                                            #String

#Here all the functions and methods used in a string.
#capitalize(), lower(), upper(), casefold(), title(), len(), type(),
#aggeregate func and search functions - min, max, count, rfind, find, index, rindex
#trimming- split, strip, partition, join()
#replacing- replace, translate(),
#endoging = format,
#basic operations - len, sorted, max, min, str, reversed, enumerate().

In [ ]:
name = "bunty"
a = "my name is {}"
print(a.format(name))

my name is bunty


In [ ]:
#to add two different strings.
first_name = "Dipak"
last_name = "Roy"
full_name = first_name+ " " +last_name
print(full_name)

Dipak Roy


In [ ]:
name = "Jonny"
b = name.format()
print("my name is {}, so, you should give respect.")

my name is {}, so, you should give respect.


In [ ]:
string_c = "i am requesting to the god, for my placement as soon as possible.     "
print(string_c.split())
print(string_c.strip())
print(string_c.replace("requesting", "begging"))
print(string_c.rfind("a"))      #it will provide the the place of the last element in the last.

['i', 'am', 'requesting', 'to', 'the', 'god,', 'for', 'my', 'placement', 'as', 'soon', 'as', 'possible.']
i am requesting to the god, for my placement as soon as possible.
i am begging to the god, for my placement as soon as possible.     
53


In [ ]:
string_b = "i wish i could change my job as soon as possible."
print(string_b.capitalize())
print(string_b.upper())
print(string_b.casefold())
print(string_b.lower())

I wish i could change my job as soon as possible.
I WISH I COULD CHANGE MY JOB AS SOON AS POSSIBLE.
i wish i could change my job as soon as possible.
i wish i could change my job as soon as possible.


In [ ]:
a_str = "I am ready to change my domain."
print(len(a_str))
print(type(a_str))
print(a_str.find("to"))
print(a_str.index("my"))
print(a_str.count("a"))  #print(count(a_str)) here i did before and it was wrong.

31
<class 'str'>
11
21
4


In [ ]:
                                                            #Lists
#all functions and methods used in a list


#Add/modify - append, extend, insert.
#for remove- remove, pop, clear.
#search - index, count                   NOTES- find method is not in the list while it is working in string.
#reorder- sort, reverse                  #NOTES- sort function is not working in terms of lists.
#copy - copy()

#basic functions- len, sorted, max, sum, all, reversed, enumerate, zip(*lists).

In [ ]:
list1 = [1, 2, 3, 2, 5, "Hello", "rohit"]
print(list1.append("Vikas"))
print(list1)

print(list1.extend("123"))
print(list1)

print(list1.insert(0,"Hooda"))
print(list1)

None
[1, 2, 3, 2, 5, 'Hello', 'rohit', 'Vikas']
None
[1, 2, 3, 2, 5, 'Hello', 'rohit', 'Vikas', '1', '2', '3']
None
['Hooda', 1, 2, 3, 2, 5, 'Hello', 'rohit', 'Vikas', '1', '2', '3']


In [ ]:
list1 = [1, 2, 3, 2, 5, "Hello", "rohit"]

# Append "Vikas" to the list
list1.append("Vikas")
print("After append:", list1)

# Add "Brother" as a single element
list1.append("Brother")  # Use append instead of extend
print("After appending 'Brother':", list1)

# Find the index of 5
index_of_5 = list1.index(5)
print("Index of 5:", index_of_5)

# Insert "Professional" at the beginning
list1.insert(0, "Professional")
print("After inserting 'Professional':", list1)

In [ ]:
name = "Sohit"
a = name.format()
print("my name is { }")


name = "Vijay"
a = "my name is {}"
print(a.format(name))

my name is { }
my name is Vijay


In [ ]:
name = "queen"
a = "my name is {}"
print(a.format(name))

my name is queen


In [ ]:
def add(x,y):
  print("The addition of these two numbers is", x+y)
add(2,3)

The addition of these two numbers is 5


In [ ]:
def marks(num):
  if num >=90:
    print("You are a brilliant student.")
  elif num>=80 and num <=89:
    print("You will be a brilliant student someday.")
  else:
    print("You need to improve yourself.")
    print("Thank you")

marks(85)

You will be a brilliant student someday.


In [ ]:
x = lambda a,b,c: (a+b)*c
x(1,2,3)


9

In [ ]:
for i in range(1,11):
  if i == 3:
    print("Skip this song.")
  else:
    print(i)

1
2
Skip this song.
4
5
6
7
8
9
10


In [ ]:
a = ["Ramayana", "Mahabharat", "Shiv Puran", "Bala Ji Maharaj"]
for i in a:
  print(i, end = " ")

Ramayana Mahabharat Shiv Puran Bala Ji Maharaj 

In [ ]:
dic = {"name": ["Ramya", "Rani", "Rosy", "Rachel"],
        "age": [23, 24, 25, 32],
        "salary": [23000, 30000, 42000, 35000]}

#for i in dic:
#  print(i)

#for i in dic:
#  print(dic[i])

#for i in dic:
#  print(dic[i][1])

Rani Rani Rani 

In [ ]:
dic = {"name": ["Ramya", "Rani", "Rosy", "Rachel"],
        "age": [23, 24, 25, 32],
        "salary": [23000, 30000, 42000, 35000]}

dic["name"][1]

'Rani'

In [ ]:
sets = {"hulk", "thor", "superman", "spiderman"}
sets.add("Batman")
sets

{'Batman', 'hulk', 'spiderman', 'superman', 'thor'}

In [ ]:
import pandas as pd
data = {"First Name": ["Rohini", "Raj", "Rani", "Aasma"],
        "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
        "Age": [23, 45, 35, 29],
        "Gender": ["Female", "Male", "Female", "Female"],
        "Salary": [45000, 49000, 56000, 34000],
        "City": ["New Delhi", "Mumbai", "Hydrabad", "New Delhi"]}

df = pd.DataFrame(data)


gp = df.groupby(["City", "Gender"])
print(gp)


                  First Name  Last Name  Age  Salary
City      Gender                                    
Hydrabad  Female           1          1    1       1
Mumbai    Male             1          1    1       1
New Delhi Female           2          2    2       2


In [ ]:
import pandas as pd

data = {
    "First Name": ["Rohini", "Raj", "Rani", "Aasma"],
    "Last Name": ["Kashyap", "Kumar", "Raj", "Sinha"],
    "Age": [23, 45, 35, 29],
    "Gender": ["Female", "Male", "Female", "Female"],
    "Salary": [45000, 49000, 56000, 34000],
    "City": ["New Delhi", "Mumbai", "Hydrabad", "New Delhi"]
}

df = pd.DataFrame(data)

# Corrected groupby code
gp = df.groupby(["City", "Gender"])
print(gp)

In [ ]:
gb = df.groupby("City").size()
gb

City
Hydrabad     1
Mumbai       1
New Delhi    2
dtype: int64

In [ ]:
#Generators = It is a special types of iterables which generates the values without storing the memory.

def count_upto(n):
  count = 1
  while count < 5:
    yield count
    count += 1
counter = count_upto(5)

for i in counter:
  print(i)

1
2
3
4


In [ ]:
#generator
def count_upto(n):
  count = 1
  while count < 5:
    yield count
    count+=1

counter = count_upto(5)
for i in counter:
  print(i)

1
2
3
4


In [ ]:
import copy
original = [1,[2,3],4]
shallow = copy.copy(original)
original[1][0] = 99
print("original:", original)
print("shallow:" ,shallow)


original = [1,[2,3],4]
deep = copy.deepcopy(original)
print("original: ", original )
print("deep copy: ", deep)

original: [1, [99, 3], 4]
shallow: [1, [99, 3], 4]
original:  [1, [2, 3], 4]
deep copy:  [1, [2, 3], 4]


In [ ]:
original = [1,[2,3],4]
deep = copy.deepcopy(original)
original[1][0] = 99
print("original: ", original )
print("Deep copy: ", deep)

original:  [1, [99, 3], 4]
Deep copy:  [1, [2, 3], 4]


In [ ]:
#Shallow copy- A shallow copy is the copy of an object that stores the reference of the original element.
#A shallow copy is the copy of an object which stores the reference of the original element.
import copy

original = [1,[2,3],4]
shallow = copy.copy(original)
original[1][0] = 99
print("original:", original)
print("shallow copy:", shallow)

original: [1, [99, 3], 4]
shallow copy: [1, [99, 3], 4]


In [ ]:
#Deep Copy-  A deep copy creates a completely independent copy of the object and all the object inside it.
original = [1,[2,3],4]
deep = copy.deepcopy(original)
original[1][0] = 99
print("original:", original)
print("Deep Copy:", deep)

original: [1, [99, 3], 4]
Deep Copy: [1, [2, 3], 4]


In [ ]:
marks = 65

In [ ]:
marks = 65
def check_marks(n):
  if n < 70:
    print("You really need to improve yourelf")
  elif n >= 70 and n <=90:
    print("You are a brillient student.")
  else:
    print("Very well")

check_marks(89)

You are a brillient student.


In [ ]:
marks = 65

def check_marks(n):  # Use the parameter 'n'
    if n < 70:
        print("You really need to improve yourself")
    elif n >= 70 and n <= 90:
        print("You are a brilliant student.")
    else:
        print("Very well")

check_marks(89)

You are a brilliant student.


In [ ]:
length = float(input("Enter the length of the rectangle: "))
breath = float(input("Enter the breath of the rectangle: "))

def area_rect(length, breath):
  area = length * breath
  return area

area_rect(length, breath)

Enter the length of the rectangle: 45.95
Enter the breath of the rectangle: 34.2345


1573.075275

In [ ]:
#Exceptional handling.
try:
  num = int(input('Enter a number: '))
  print(10/num)
except ZeroDivisionError:
  print("Cannot divided by ZERO.")
except ValueError:
  print("Invalid Input")
finally:
  print("Program Completed!")


Enter a number: ]
Invalid Input
Program Completed!


In [ ]:
name = "jatin"
place = "delhi"
age = 30
print(name)
print(place)
print(age)

jatin
delhi
30


In [ ]:
a = 12
b = 23
a,b = b,a
print(a)
print(b)

23
12


In [ ]:
a = 1.23
b = int(a)
a = int(b)
print(a)

1


In [ ]:
name = input("Enter the name of student: ")
age = int(input("Enter the age of the student: "))
address = input("Enter the address of the student: ")
roll_no = input("Enter the roll number of the student: ")


Enter the name of student: Jason
Enter the age of the student: 15
Enter the address of the student: D- 23 Lodhi Garden Delhi = 110082
Enter the roll number of the student: 21


In [ ]:
user_input = int(input("Enter any number here: "))
converted_input = float(user_input)
print(converted_input)

Enter any number here: 2
2.0


In [ ]:
#for i in range(1,11):
#  print(i)

#for i in range(1,5):
# if i == 2:
#    print("Skip this part.")
#  else:
#    print(i)

#n = 10
#for i in range(1,11):
#  print(n*i)

for i in range(1,3):
  for j in range(1,5):
    print(j, end = " ")

1 2 3 4 1 2 3 4 

In [ ]:
#n = 1
#while n < 5:
#  print(n)
#  n += 1

#n = 3
#a = 1
#while a <= 10:
#  print(n*a)
#  a += 1

3
6
9
12
15
18
21
24
27
30


In [ ]:
#generator- it gives us the value without storing the memory.
def count_upto(n):
  count = 1
  while count < 5:
    yield count
    count+=1

counter = count_upto(5)
for i in counter:
  print(i)

1
2
3
4


In [ ]:
name = "Rohan"
age = 34
address = "D-45 Great Lake New Delhi"
print(name)
print(age)
print(address)

Rohan
34
D-45 Great Lake New Delhi


In [ ]:
#we can swap two variables by creating a temperory variable.
a = 3
b = 9
temp = a
a = b
b = temp
print(a)
print(b)

9
3


In [ ]:
#also
a = 3
b = 4
a,b = b,a
print(a)
print(b)

4
3


In [ ]:
a = 1.23
a = int(a)
print(a)

1


In [ ]:
name = input("Enter the name here: ")
age = int(input("Enter the age here: "))
roll_no = int(input("Enter the roll number here: "))
address = input("Enter your address here: ")

Enter the name here: john
Enter the age here: 34
Enter the roll number here: 32
Enter your address here: D-43 Lodhi Garden Delhi- 110032


In [ ]:
a = int(input("Enter any number here: "))
a = float(a)
print(a)

Enter any number here: 3
3.0


In [ ]:
#To check the number is even or odd.
num = int(input("Enter the number here: "))
if num%2 ==0:
  print("It is a positive number.")
else:
  print("Negative number")

Enter the number here: 3
Negative number


In [ ]:
#to check the number is positive or not.
number = int(input("Enter any number here: "))
if number >=1 :
  print("It is a positive number")
else:
  print("Negative number")

Enter any number here: -1
Negative number


In [ ]:
#Creating an area calculator.
#press 1 to get the area of the square.
#press 2 to get the area of the circle.

area = int(input("Enter the number in between 1 and 3: "))
if area == 1:
  side = float(input("Enter the side of the square: "))
  area_square = side*side
  print(area_square)
elif area == 2:
  radius = float(input("Enter the radius of the circle: "))
  area_circle = 3.14*radius*radius
  print(area_circle)

Enter the number in between 1 and 3: 2
Enter the radius of the circle: 7
153.86


In [ ]:
#to check whether the given number is vowel or not.
letters = input("Enter any letter here: ")
if letters in "AEIOUaeiou":
  print('it is a vowel')
else:
  print("it is a consonent")

Enter any letter here: c
it is a consonent


In [ ]:
def number(n):
  if n>=0 and n<=9:
    print("It is a single digit number.")
  elif n>=10 and n<=99:
    print("It is a double digit number.")
  elif n >=100 and n <=999:
    print("It is a three digit number.")
  else:
    print("INVALID OUTPUT!!")

number(33)

It is a double digit number.


In [ ]:
#to find the sum of all even numbers till 50.
sum = 0
for i in range(1,51):
  if i % 2 == 0:
    sum += i

print("The sum of 50 even numbers is ", sum)

The sum of 50 even numbers is  650


In [ ]:
#to write first 20 numbers and their squares.
for i in range(1,21):
  print(i, "=", i*i)

1 = 1
2 = 4
3 = 9
4 = 16
5 = 25
6 = 36
7 = 49
8 = 64
9 = 81
10 = 100
11 = 121
12 = 144
13 = 169
14 = 196
15 = 225
16 = 256
17 = 289
18 = 324
19 = 361
20 = 400


In [ ]:
#sum of first 20 odd numbers.
sum = 0
n = 0
while n<=20:
  if n % 2 != 0:
    sum += n
  n += 1
print(sum)

100


In [ ]:
sum = 0
n = 0
while n < 20:
  if n%2 != 0:
    sum += n
  n += 1

print("The sum of the first 10 odd numbers is", sum)


The sum of the first 10 odd numbers is 100


In [ ]:
for i in range(1,101):
  if i%8== 0 and i%12 == 0:
    print(i)

24
48
72
96


In [ ]:
A = "Why fit in, when you are born to stand out!  "
len(A)
A.lower()
A.upper()
A.title()
A.find("fit")
A.index('fit')
A.count("o")

4

In [ ]:
a = "123hello"
a.isalnum()
a.isdigit()
a.isnumeric()
a.isdecimal()
a.islower()

True

In [ ]:
a = "Ballot   "
a.endswith("t")
a.startswith("B")
a.swapcase()
a.strip()
#a.split("#")
a.rfind("o")
a.rindex("o")
a.replace("o","e")

'Ballet   '

In [ ]:
strr = "My name is jonny."
strr.replace("jonny", "Honey")

'My name is Honey.'

In [ ]:
a = "Harry Potter and the Goblet of fire."
b = "0123456789"
print(a)

Harry Potter and the Goblet of fire.


In [ ]:

#fibonacci series.
#upto 10 numbers.
a = 0
b = 1
n = int(input('Enter any number here: '))
if n == 1:
  print(n)
  c = a + b
  a = b
  b = c


Enter any number here: 4


In [ ]:
#fibonacci series
a = 0
b = 1
for i in range(1,11):
  print(a, end = " ")
  c = a + b
  a = b
  b = c

0 1 1 2 3 5 8 13 21 34 

In [ ]:
# Fibonacci series up to 10 numbers
a = 0  # First Fibonacci number
b = 1  # Second Fibonacci number

print("Fibonacci series up to 10 numbers:")
for i in range(10):  # Loop 10 times to generate 10 numbers
    print(a, end=" ")  # Print the current number
    c = a + b  # Calculate the next Fibonacci number
    a = b  # Move 'b' to 'a'
    b = c  # Move 'c' (next number) to 'b'

Fibonacci series up to 10 numbers:
0 1 1 2 3 5 8 13 21 34 

In [ ]:
# Fibonacci series using user input
n = int(input("Enter the number of terms for the Fibonacci series: "))

a, b = 0, 1  # First two terms of the Fibonacci series

print("Fibonacci series:")
for i in range(n):
    print(a)  # Print the current term
    a, b = b, a + b  # Update 'a' and 'b' for the next terms

Enter the number of terms for the Fibonacci series: 10
Fibonacci series:
0
1
1
2
3
5
8
13
21
34


In [ ]:
#fibonacci series
n = int(input("Enter any number terms for fibonacci series: "))

a,b = 0,1
for i in range(n):
  print(a)
  a,b = b,a+b

Enter any number terms for fibonacci series: 10
0
1
1
2
3
5
8
13
21
34


In [ ]:
#fibonacci series
n = int(input("Enter the number here: "))
a,b = 0,1
for i in range(n):
  print(a)
  a,b = b,a+b

Enter the number here: 10
0
1
1
2
3
5
8
13
21
34


In [ ]:
number = int(input("Enter any number here : "))
if number % number != 0:



In [ ]:
#Fibonacci series
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a, end = " ")
    c = a + b
    a = b
    b = c

fibonacci(10)

0 1 1 2 3 5 8 13 21 34 

In [ ]:
n = int(input("Enter any number here: "))

a,b = 0,1
for i in range(n):
  print(a)
  a,b = b,a+b


Enter any number here: 10
0
1
1
2
3
5
8
13
21
34


In [ ]:
n = int(input("Enter a number till you want a fibonacci series: "))
a,b = 0,1
for i in range(n):
  print(a, end = " ")
  a,b = b,a+b

Enter a number till you want a fibonacci series: 10
0 1 1 2 3 5 8 13 21 34 

In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a, end = " ")
    c = a + b
    a = b
    b = c

fibonacci(10)

0 1 1 2 3 5 8 13 21 34 

In [ ]:
n = int(input("Enter number"))
a,b = 0,1
for i in range(n):
  print(a)
  a,b = b,a+b

Enter number10
0
1
1
2
3
5
8
13
21
34


In [ ]:
#to find sum of all even numbers till 50.
sum = 0
for i in range(1,51):
  if i % 2 ==0:
    sum += i
print(sum)

650


In [ ]:
#first 20 numbers and their squared values.
for i in range(1,21):
  squared_numbers = i*i
  print("The sum of squared numbers", i,"=", squared_numbers)

The sum of squared numbers 1 = 1
The sum of squared numbers 2 = 4
The sum of squared numbers 3 = 9
The sum of squared numbers 4 = 16
The sum of squared numbers 5 = 25
The sum of squared numbers 6 = 36
The sum of squared numbers 7 = 49
The sum of squared numbers 8 = 64
The sum of squared numbers 9 = 81
The sum of squared numbers 10 = 100
The sum of squared numbers 11 = 121
The sum of squared numbers 12 = 144
The sum of squared numbers 13 = 169
The sum of squared numbers 14 = 196
The sum of squared numbers 15 = 225
The sum of squared numbers 16 = 256
The sum of squared numbers 17 = 289
The sum of squared numbers 18 = 324
The sum of squared numbers 19 = 361
The sum of squared numbers 20 = 400


In [ ]:
#to find the sum of first 10 odd numbers.
sum = 0
for i in range(1,20):
  if i%2 != 0:
    sum += i
print(sum)


100


In [ ]:
for i in range(1,101):
  if i % 8 ==0 and i % 12 == 0:
    print(i, end = " ")

24 48 72 96 

In [ ]:
strring = "Hey buddy, i hope you are doing fine."
len(strring)
strring.count("d")
strring.lower()
strring.upper()
strring.swapcase()
strring.index("i")
strring.rfind("i")   #it will find the last i that comes in the string.
strring.find("i")

11

In [ ]:
s = "HelloFriends123"
s.islower()
s.isalnum()
s.isnumeric()
s.isdigit()
s.isupper()

False

In [ ]:
#to strip and split
a = "       hey#friends."
#a.strip()
a.split("#")

['       hey', 'friends.']

In [ ]:
a = "#hey#hello#hi#how#are#you"
a.split("#")

['', 'hey', 'hello', 'hi', 'how', 'are', 'you']

In [ ]:
#replace method.
name_string = "My name is Honey Singh"
name_string.replace("Honey Singh", "Badshaw")

'My name is Badshaw'

In [ ]:
##not done so go and check again.
a = "Hello Mohan "
name = "Madan"
name = a.format("Madan")
print("My name is ", {name})

My name is  {'Hello Mohan '}


In [ ]:
#to check prime number.
def check_prime(n):
  if n %

In [ ]:
#to get the fibonacci series
a,b = 0,1
for i in range(1,11):
  print(a)
  c = a + b
  a = b
  b = c

0
1
1
2
3
5
8
13
21
34


In [ ]:
a = 0
b = 1

print(a)
print(b)
for i in range(2,11):
  c = a + b
  a = b
  b = c
  print(c)

0
1
1
2
3
5
8
13
21
34
55


In [ ]:
num = int(input("enter any number here: "))

for i in range(2,n):
  if num%i == 0:
    print("It is not a prime number")
  else:
    print("It is a prime number!")


enter any number here: 24
It is not a prime number


In [ ]:
#palindrome
num = int(input("enter number here: "))
temp = num
rev = 0
while num >0:
  digit = num%10
  rev = rev*10+digit
  num = num//10
if rev == temp:
  print("It is a palindrome")
else:
  print("Not a palindrome.")

enter number here: 121
It is a palindrome


In [ ]:
a = "ootd.bts.happy"
a.split(".")

['ootd', 'bts', 'happy']

In [ ]:
a = input("Enter anything here: ")
b = sorted(a)
b

Enter anything here: 4321


['1', '2', '3', '4']

In [ ]:
a = "Hello"
a.replace("e", " ")

'H llo'

In [ ]:
c = "Bididybodidydadady"
c.count("dy")

3

In [ ]:
user_input = input("Enter any number here:")
rev_inp = user_input[::-1]
print(rev_inp)

Enter any number here: bcda
adcb


In [ ]:
#to find number of vowel
letter =

TypeError: 'str' object is not callable

In [ ]:
letters = input("Enter any letter here:")
if letters in "aeiouAEIOU":
    print("It is a vowel")
else:
    print("It is not a vowel but a consonant.")

TypeError: 'str' object is not callable

In [ ]:
letters = input("Enter any letter here: ")
if letters in "aeiouAEIOU":
    print("It is a vowel")
else:
    print("It is not a vowel but a consonant.")

TypeError: 'str' object is not callable

In [ ]:
fib_num = int(input("Enter the number till you want the fibonacci series."))
a,b = 0,1
for i in range(fib_num):
  print(a, end = " ")
  a,b = b,a+b



Enter the number till you want the fibonacci series.10
0 1 1 2 3 5 8 13 21 34 

In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a)
    a,b = b,a+b
fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [ ]:
n = int(input("The fibonacci series of the number: "))
a,b = 0,1
for i in range(n):
  print(a, end = " ")
  a,b = b,a+b


The fibonacci series of the number: 10
0 1 1 2 3 5 8 13 21 34 

In [ ]:
#to find number of vowels in a string.
a = "Hey brother, i hope you are doing fine."
v = a.count("a")
o = a.count("A")
w = a.count("e" or "E")
e = a.count("i" or "I")
print(v+o+w+e)


9


In [ ]:
#to find the number of vowels.
a = input("Enter anything here: ")
vowels = 0
for i in a:
  if i == "A" or i == "a" or i == "e" or i == "E" or i == "i" or i == "I" or i == "O" or i == "o" or i == "u" or i == "U":
    vowels += 1
print("The number of vowels in this sentence is", vowels)


Enter anything here: hey borther
The number of vowels in this sentence is 3


In [ ]:
a = "hey buddy WHAT are you tdont"
a.istitle()

False

In [ ]:
listt = ['spiderman', 'superman']
listt.append("batman")
listt

['spiderman', 'superman', 'batman']

In [ ]:
listt.remove("spiderman")

In [ ]:
listt

['superman', 'batman']

In [ ]:
a = "hey brother"
vowel = 0
for i in a:
  if i == "A" or i == "a" or i == "e" or i == "E" or i == "i" or i == "I" or i == "O" or i == "o" or i == "u" or i == "U":
    vowel += 1
print(vowel)

3


In [ ]:
#Write a program to check whether a given number is even or odd
num = int(input("Enter any number here: "))
if num % 2 == 0:
  print("this is a even number.")
else:
  print("It is a odd number.")

Enter any number here: 3
It is a odd number.


In [ ]:
#Write a program to swap two variables without using a temporary variable.
a = 3
b = 4
a,b = b,a
print(a)
print(b)

4
3


In [ ]:
#To find the factorial of the number by using the recursion.
def fact(n):
  if n ==1:
    return n
  elif n == 2:
    return 2
  else:
    if n > 2:
      while n<5:
        result= n*(n-1)
        n +=1
        print(result)

fact(5)

In [ ]:
#To get the factorial of a number.
def fact(n):
  if n == 0 or n == 1:
    return n
  else:
    return n*fact(n-1)
fact(4)

24

In [ ]:
#fibonacci series upto n.
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a, end = " ")
    c = a + b
    a = b
    b = c
fibonacci(10)

0 1 1 2 3 5 8 13 21 34 

In [ ]:
#to check a prime number.
num = int(input("Enter any number here: "))
if num == 0 or num == 1:
  print("It is not a prime number.")
else:
  for i in range(2, num):
    if num % i == 0:
      print("It is not a prime number")
      break
    else:
      print("It is a prime number.")

Enter any number here: 9
It is a prime number.
It is not a prime number


In [ ]:
def to_checkprime(n):
  if n ==1:
    print("It is not a prime number.")
  elif for i in n:
    n % i == 0:
    print("It is not prime")
  else:
    print("Prime number")

SyntaxError: invalid syntax (<ipython-input-41-8a51eeff9625>, line 4)

In [ ]:
n = int(input("Enter any number here to check prime: "))
if n <= 1:
  print("It is not a prime number.")
else:
  for i in range(2,n):
    if n%i==0:
      print("It is also not a prime number.")
      break
    else:
      print("It is a prime number.")

Enter any number here to check prime: 7
It is a prime number.
It is a prime number.
It is a prime number.
It is a prime number.
It is a prime number.


In [ ]:
for i in range(2,11):
  print(i)

2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(1,11):
  if i == 6:
    print("Skip this part")
  else:
    print(i)

1
2
3
4
5
Skip this part
7
8
9
10


In [ ]:
def add(x,y):
  print(x+y)
add(1,2)

3


In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c
fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [ ]:
#to find sum of even numbers.
sum = 0
for i in range(1,51):
  if i % 2 == 0:
    sum += i
print(sum)

650


In [ ]:
#to check the prime number.
n = int(input("Enter any number to check prime: "))
if n == 1:
  print(n)
else:
  for i in range(2,n):
    if n % i == 0:
      print("It is not a prime number")
      break
    else:
      print("It is a prime number.")


Enter any number to check prime: 7
It is a prime number.
It is a prime number.
It is a prime number.
It is a prime number.
It is a prime number.


In [ ]:
#to find the factorial of any number.
factt = 0
def fact(n):
  if n == 1:
    print(n)
  else:
    for i in range(2,n):


TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

In [ ]:
def fact(n):
  if n == 1 or n == 0:
    return n
  else:
    return n*fact(n-1)
fact(5)

120

In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a, end = " ")
    c = a+b
    a = b
    b = c
fibonacci(10)

0 1 1 2 3 5 8 13 21 34 

In [ ]:
#factorial
sum = 0
def fact(n):
  if n == 1 or n == 0:
    return n
  else:
    sum = n*fact(n-1)
    return sum
fact(5)


120

In [ ]:
#lambda function.
a = lambda a,b,c: (a+b)*c
print(a(1,2,3))

9


In [ ]:
a = lambda b: 5*b
print(a(3))

15


In [ ]:
for i in range(1,11):
  if i == 5:
    print("Skip this part")
  else:
    print(i)

1
2
3
4
Skip this part
6
7
8
9
10


In [ ]:
#to find the maximum of three numbers.
def max_num(a,b,c):
  if a > b and b < c:
    print(a, "is the maximum")
  elif a < b and b < c:
    print(c, "is the max number")
  else:
    print(b, "is the maximum number")
max_num(4,2,3)

4 is the maximum


In [ ]:
def squared_num(n):
  for i in range(1,n):
    print("The squared number of", i, "is", i*i)
squared_num(3)

The squared number of 1 is 1
The squared number of 2 is 4


In [ ]:
def create_list():
  l = []
  for i in range(1,31):
    l.append(i*i)
  return l
create_list()

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900]

In [ ]:
def fact(n):
  if n == 1:
    return n
  else:
    return(n*fact(n-1))
fact(3)

6

In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a)
    c = a+b
    a = b
    b = c
fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [ ]:
#numpy
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
arry = np.array([[1,2],[3,4]])
print(arry)

[[1 2]
 [3 4]]


In [ ]:
arr2 = np.array([[5,6],[7,8]])

In [ ]:
print(arry)
print(arr2)
print(arry + arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([3])
print(arr1*arr2)

[[ 3  6]
 [ 9 12]]


In [ ]:
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)
print(arr1.ndim)
print(arr1.astype)

(2, 2)
4
int64
2
<built-in method astype of numpy.ndarray object at 0x7926a693fb10>


In [ ]:
arr1 = np.array([1,2,3,4])
print(arr1.astype(int))
print(arr1.dtype)

[1 2 3 4]
int64


In [ ]:
x = 24
print(x)
def value():
  x = 25
  return x
print(value())
print(x)


24
25
24


In [ ]:
x = 23
print(x)


def hello():
    global x
    x = 24
    return x

print(hello())
print(x)

23
24
24


In [ ]:
x = 23
print(x)  # Prints 23

def hello():
    global x  # Declare x as global
    x = 24    # Modify the global variable x
    return x

print(hello())  # Prints 24
print(x)

23
24
24


In [ ]:
x = 12
print(x)
def hello():
  x = 23
  return x
print(hello())
print(x)

12
23
12


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
path = "/content/ESD (1).xlsx"
df = pd.read_excel(path)
df

EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT   
1    E04105    Theodore Dinh       Technical Architect          IT   
2    E02572     Luna Sanders                  Director     Finance   
3    E02832  Penelope Jordan  Computer Systems Manager          IT   
4    E01639        Austin Vo               Sr. Analyst     Finance   
..      ...              ...                       ...         ...   
995  E03094     Wesley Young               Sr. Analyst   Marketing   
996  E01909     Lillian Khan                   Analyst     Finance   
997  E04398      Oliver Yang                  Director   Marketing   
998  E02521      Lily Nguyen               Sr. Analyst     Finance   
999  E03545      Sofia Cheng            Vice President  Accounting   

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604   
1             Manufacturing    Male      Asian   59 1997-11-29          99975   
2       Speciality Products  Female  Caucasian   50 2006-10-26         163099   
3             Manufacturing  Female  Caucasian   26 2019-09-27          84913   
4             Manufacturing    Male      Asian   55 1995-11-20          95409   
..                      ...     ...        ...  ...        ...            ...   
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427   
996     Speciality Products  Female      Asian   44 2010-05-31          47387   
997     Speciality Products    Male      Asian   31 2019-06-10         176710   
998     Speciality Products  Female      Asian   33 2012-01-28          95960   
999               Corporate  Female      Asian   63 2020-07-26         216195   

     Bonus %        Country       City  Exit Date  
0       0.15  United States    Seattle 2021-10-16  
1       0.00          China  Chongqing        NaT  
2       0.20  United States    Chicago        NaT  
3       0.07  United States    Chicago        NaT  
4       0.00  United States    Phoenix        NaT  
..       ...            ...        ...        ...  
995     0.00  United States   Columbus        NaT  
996     0.00          China    Chengdu 2018-01-08  
997     0.15  United States      Miami        NaT  
998     0.00          China    Chengdu        NaT  
999     0.31  United States      Miami        NaT  

[1000 rows x 14 columns]

In [ ]:
df.head(3)

EEID      Full Name            Job Title Department  \
0  E02387    Emily Davis           Sr. Manger         IT   
1  E04105  Theodore Dinh  Technical Architect         IT   
2  E02572   Luna Sanders             Director    Finance   

            Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0  Research & Development  Female      Black   55 2016-04-08         141604   
1           Manufacturing    Male      Asian   59 1997-11-29          99975   
2     Speciality Products  Female  Caucasian   50 2006-10-26         163099   

   Bonus %        Country       City  Exit Date  
0     0.15  United States    Seattle 2021-10-16  
1     0.00          China  Chongqing        NaT  
2     0.20  United States    Chicago        NaT

In [ ]:
df.isnull().sum()

EEID               0
Full Name          0
Job Title          0
Department         0
Business Unit      0
Gender             0
Ethnicity          0
Age                0
Hire Date          0
Annual Salary      0
Bonus %            0
Country            0
City               0
Exit Date        915
dtype: int64

In [ ]:
df["EEID"].duplicated().sum()

89

In [ ]:
df.drop_duplicates("EEID")

EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT   
1    E04105    Theodore Dinh       Technical Architect          IT   
2    E02572     Luna Sanders                  Director     Finance   
3    E02832  Penelope Jordan  Computer Systems Manager          IT   
4    E01639        Austin Vo               Sr. Analyst     Finance   
..      ...              ...                       ...         ...   
995  E03094     Wesley Young               Sr. Analyst   Marketing   
996  E01909     Lillian Khan                   Analyst     Finance   
997  E04398      Oliver Yang                  Director   Marketing   
998  E02521      Lily Nguyen               Sr. Analyst     Finance   
999  E03545      Sofia Cheng            Vice President  Accounting   

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604   
1             Manufacturing    Male      Asian   59 1997-11-29          99975   
2       Speciality Products  Female  Caucasian   50 2006-10-26         163099   
3             Manufacturing  Female  Caucasian   26 2019-09-27          84913   
4             Manufacturing    Male      Asian   55 1995-11-20          95409   
..                      ...     ...        ...  ...        ...            ...   
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427   
996     Speciality Products  Female      Asian   44 2010-05-31          47387   
997     Speciality Products    Male      Asian   31 2019-06-10         176710   
998     Speciality Products  Female      Asian   33 2012-01-28          95960   
999               Corporate  Female      Asian   63 2020-07-26         216195   

     Bonus %        Country       City  Exit Date  
0       0.15  United States    Seattle 2021-10-16  
1       0.00          China  Chongqing        NaT  
2       0.20  United States    Chicago        NaT  
3       0.07  United States    Chicago        NaT  
4       0.00  United States    Phoenix        NaT  
..       ...            ...        ...        ...  
995     0.00  United States   Columbus        NaT  
996     0.00          China    Chengdu 2018-01-08  
997     0.15  United States      Miami        NaT  
998     0.00          China    Chengdu        NaT  
999     0.31  United States      Miami        NaT  

[911 rows x 14 columns]

In [ ]:
df["Gender"].isnull().sum()

0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   EEID           1000 non-null   object        
 1   Full Name      1000 non-null   object        
 2   Job Title      1000 non-null   object        
 3   Department     1000 non-null   object        
 4   Business Unit  1000 non-null   object        
 5   Gender         1000 non-null   object        
 6   Ethnicity      1000 non-null   object        
 7   Age            1000 non-null   int64         
 8   Hire Date      1000 non-null   datetime64[ns]
 9   Annual Salary  1000 non-null   int64         
 10  Bonus %        1000 non-null   float64       
 11  Country        1000 non-null   object        
 12  City           1000 non-null   object        
 13  Exit Date      85 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2), object(9)
memory usage: 109.5

In [ ]:
df.describe()

Age                   Hire Date  Annual Salary      Bonus %  \
count  1000.000000                        1000    1000.000000  1000.000000   
mean     44.382000  2012-04-07 02:54:14.400000  113217.365000     0.088660   
min      25.000000         1992-01-09 00:00:00   40063.000000     0.000000   
25%      35.000000         2007-02-14 00:00:00   71430.250000     0.000000   
50%      45.000000         2014-02-15 12:00:00   96557.000000     0.000000   
75%      54.000000         2018-06-22 00:00:00  150782.250000     0.150000   
max      65.000000         2021-12-26 00:00:00  258498.000000     0.400000   
std      11.246981                         NaN   53545.985644     0.117856   

                           Exit Date  
count                             85  
mean   2016-11-02 18:04:14.117647104  
min              1994-12-18 00:00:00  
25%              2014-12-25 00:00:00  
50%              2019-05-23 00:00:00  
75%              2021-04-09 00:00:00  
max              2022-08-17 00:00:00  
std                              NaN

In [ ]:
df.describe().T

count                           mean                  min  \
Age            1000.0                         44.382                 25.0   
Hire Date        1000     2012-04-07 02:54:14.400000  1992-01-09 00:00:00   
Annual Salary  1000.0                     113217.365              40063.0   
Bonus %        1000.0                        0.08866                  0.0   
Exit Date          85  2016-11-02 18:04:14.117647104  1994-12-18 00:00:00   

                               25%                  50%                  75%  \
Age                           35.0                 45.0                 54.0   
Hire Date      2007-02-14 00:00:00  2014-02-15 12:00:00  2018-06-22 00:00:00   
Annual Salary             71430.25              96557.0            150782.25   
Bonus %                        0.0                  0.0                 0.15   
Exit Date      2014-12-25 00:00:00  2019-05-23 00:00:00  2021-04-09 00:00:00   

                               max           std  
Age                           65.0     11.246981  
Hire Date      2021-12-26 00:00:00           NaN  
Annual Salary             258498.0  53545.985644  
Bonus %                        0.4      0.117856  
Exit Date      2022-08-17 00:00:00           NaN

In [ ]:
df.columns

Index(['EEID', 'Full Name', 'Job Title', 'Department', 'Business Unit',
       'Gender', 'Ethnicity', 'Age', 'Hire Date', 'Annual Salary', 'Bonus %',
       'Country', 'City', 'Exit Date'],
      dtype='object')

In [ ]:
df["Department"]
df["Annual Salary"]
df["Department_salary"] = df["Department"] + " " + df["Annual Salary"].astype(str)

In [ ]:
df

EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT   
1    E04105    Theodore Dinh       Technical Architect          IT   
2    E02572     Luna Sanders                  Director     Finance   
3    E02832  Penelope Jordan  Computer Systems Manager          IT   
4    E01639        Austin Vo               Sr. Analyst     Finance   
..      ...              ...                       ...         ...   
995  E03094     Wesley Young               Sr. Analyst   Marketing   
996  E01909     Lillian Khan                   Analyst     Finance   
997  E04398      Oliver Yang                  Director   Marketing   
998  E02521      Lily Nguyen               Sr. Analyst     Finance   
999  E03545      Sofia Cheng            Vice President  Accounting   

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604   
1             Manufacturing    Male      Asian   59 1997-11-29          99975   
2       Speciality Products  Female  Caucasian   50 2006-10-26         163099   
3             Manufacturing  Female  Caucasian   26 2019-09-27          84913   
4             Manufacturing    Male      Asian   55 1995-11-20          95409   
..                      ...     ...        ...  ...        ...            ...   
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427   
996     Speciality Products  Female      Asian   44 2010-05-31          47387   
997     Speciality Products    Male      Asian   31 2019-06-10         176710   
998     Speciality Products  Female      Asian   33 2012-01-28          95960   
999               Corporate  Female      Asian   63 2020-07-26         216195   

     Bonus %        Country       City  Exit Date  Department_salary  
0       0.15  United States    Seattle 2021-10-16          IT 141604  
1       0.00          China  Chongqing        NaT           IT 99975  
2       0.20  United States    Chicago        NaT     Finance 163099  
3       0.07  United States    Chicago        NaT           IT 84913  
4       0.00  United States    Phoenix        NaT      Finance 95409  
..       ...            ...        ...        ...                ...  
995     0.00  United States   Columbus        NaT    Marketing 98427  
996     0.00          China    Chengdu 2018-01-08      Finance 47387  
997     0.15  United States      Miami        NaT   Marketing 176710  
998     0.00          China    Chengdu        NaT      Finance 95960  
999     0.31  United States      Miami        NaT  Accounting 216195  

[1000 rows x 15 columns]

In [ ]:
top_salarybydept = (df.sort_values(by = ["Department", "Annual Salary"], ascending = [True, False]).groupby("Department").head(3))
print(top_salarybydept)

       EEID          Full Name       Job Title       Department  \
232  E04742       Kinsley Vega  Vice President       Accounting   
672  E02563        Emily Clark  Vice President       Accounting   
803  E03289    Christopher Lam  Vice President       Accounting   
220  E00917        Skylar Bell  Vice President      Engineering   
657  E02825           Wyatt Li  Vice President      Engineering   
27   E00154         Wyatt Chin  Vice President      Engineering   
260  E04103      Isabella Soto  Vice President          Finance   
462  E03226      Angel Stewart  Vice President          Finance   
177  E01546         Maria Hong  Vice President          Finance   
395  E02599       Daniel Huang  Vice President  Human Resources   
741  E02391     Natalia Santos  Vice President  Human Resources   
63   E02112  Christian Sanders  Vice President  Human Resources   
610  E04170       Grayson Chin  Vice President               IT   
483  E01070      Grayson Brown  Vice President               I

In [ ]:
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c
fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [ ]:
def fact(n):
  if n == 1 or n == 1:
    return n
  else:
    return (n*fact(n-1))
fact(4)

24

In [ ]:
#write a program to sort a dict by values.
a = {"a": 1, "b": 4, "c": 2}
b = sorted(a.values())
print(b)

[1, 2, 4]


In [ ]:

a = {}
for i in range(1,16):
  a[i] = i*i
print(a)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}
